<?php

declare(strict_types=1);

/**
 * Default settings for the Polish market.
 *
 * These are applied on first activation. Each key maps to a WordPress option.
 * Values are only set if the option does not already exist.
 */
return [
    // General.
    'polski_general' => [
        'small_business' => false,
        'dispute_resolution_enabled' => true,
        'dispute_resolution_text' => 'Platforma ODR: https://ec.europa.eu/consumers/odr',
        'admin_pages_generated_notice' => 'Gotowe! Wygenerowaliśmy dla Ciebie wstępne szkice stron prawnych. Przejrzyj je, dostosuj do swoich potrzeb i śmiało opublikuj.',
        'admin_modules_saved_notice' => 'Moduły zapisane.',
        'admin_setup_note_title' => 'Skonfiguruj Polski dla Twojego sklepu',
        'admin_setup_note_content' => 'Jeszcze chwila i sklep będzie gotowy. Przejrzyj moduły, ustaw strony prawne i domknij konfigurację w panelu Polski.',
        'admin_setup_note_button' => 'Otwórz konfigurację Polski',
        'admin_status_active' => 'Aktywna',
        'admin_status_inactive' => 'Wyłączona',
        'admin_status_unconfigured' => 'Nieskonfigurowany',
        'admin_legal_pages_card_title' => 'Strony prawne',
        'admin_legal_pages_card_progress' => 'Masz już za sobą {done} z {total} kroków. Znakomicie!',
        'admin_vat_card_title' => 'Wyświetlanie podatku',
        'admin_vat_small_business_text' => 'Zwolnienie podmiotowe (art. 113)',
        'admin_vat_standard_text' => 'Standardowy VAT',
        'admin_doi_card_title' => 'Podwójna weryfikacja (DOI)',
        'admin_legal_pages_section_title' => 'Strony prawne',
        'admin_legal_pages_table_page' => 'Strona',
        'admin_legal_pages_table_status' => 'Status',
        'admin_legal_pages_published' => 'Opublikowana',
        'admin_legal_pages_draft' => 'Szkic',
        'admin_legal_pages_missing' => 'Nie utworzona',
        'admin_edit_button_text' => 'Edytuj',
        'admin_generate_pages_empty_text' => 'Nie utworzono jeszcze stron prawnych. Wygeneruj je, aby rozpocząć.',
        'admin_generate_pages_button_text' => 'Wygeneruj strony prawne',
        'admin_next_steps_title' => 'Kolejne kroki',
        'admin_next_steps_publish_pages' => 'Opublikuj swoje strony prawne, Regulamin, Politykę prywatności, Prawo odstąpienia i Reklamacje.',
        'admin_next_steps_tax' => 'Skonfiguruj <a href="%s">stawki VAT</a> w WooCommerce dla polskiego rynku, 23%%, 8%%, 5%% i 0%%.',
        'admin_next_steps_shipping' => 'Skonfiguruj <a href="%s">strefy wysyłki</a> dla dostaw w Polsce.',
        'admin_next_steps_products' => 'Uzupełnij dane produktów, dodaj ceny jednostkowe i czasy dostawy w <a href="%s">zakładce Polski</a> dla każdego produktu.',
        'admin_next_steps_checkout' => 'Przetestuj checkout, dodaj produkt do koszyka i sprawdź checkboxy prawne oraz tekst przycisku na <a href="%s">stronie zamówienia</a>.',
        'admin_omnibus_plugin_detected_text' => 'wykryta, dane synchronizowane',
        'admin_omnibus_plugin_missing_text' => 'niezainstalowana',
        'admin_omnibus_no_external_text' => 'Żadna zewnętrzna wtyczka Omnibus nie jest zainstalowana. Polski używa wbudowanego systemu śledzenia cen.',
        'admin_omnibus_external_active_text' => 'Zewnętrzna wtyczka wykryta. Polski korzysta z jej danych zamiast wbudowanego systemu.',
        'admin_integration_detected_text' => 'wykryta, integracja aktywna',
        'admin_integration_missing_text' => 'niewykryta',
        'admin_wpdesk_no_external_text' => 'Nie wykryto wspieranych wtyczek WP Desk. Polski działa nadal samodzielnie.',
        'admin_wpdesk_external_active_text' => 'Wykryto wspierane wtyczki WP Desk. Polski może dopasować integrację do checkoutu, cookies i GPSR.',
        'admin_payment_no_external_text' => 'Nie wykryto wspieranych polskich bramek płatności. Polski używa własnych ustawień checkoutu bez dodatkowych integracji.',
        'admin_payment_external_active_text' => 'Wykryto polskie bramki płatności. Polski może dopasować checkout i komunikaty prawne do aktywnych metod.',
    ],

    // Price display.
    'polski_prices' => [
        'tax_display_mode' => 'brutto',
        'unit_price_enabled' => true,
        'unit_price_text' => '{price} / {unit}',
        'shipping_costs_notice_enabled' => true,
        'shipping_costs_text' => 'zzgl. kosztów wysyłki',
    ],

    // Omnibus directive.
    'polski_omnibus' => [
        'enabled' => true,
        'days' => 30,
        'display_text' => 'Najniższa cena z ostatnich {days} dni: {price}',
        'display_on_sale_only' => true,
        'prune_after_days' => 90,
    ],

    // Checkout.
    'polski_checkout' => [
        'order_button_text' => 'Zamawiam z obowiązkiem zapłaty',
        'terms_checkbox_enabled' => true,
        'terms_checkbox_label' => 'Zapoznałem się i akceptuję <a href="%s" target="_blank">Regulamin sklepu</a>.',
        'terms_checkbox_error' => 'Musisz zaakceptować Regulamin, aby złożyć zamówienie.',
        'terms_checkbox_description' => 'Akceptacja Regulaminu sklepu.',
        'privacy_checkbox_enabled' => true,
        'privacy_checkbox_label' => 'Zapoznałem się i akceptuję <a href="%s" target="_blank">Politykę prywatności</a>.',
        'privacy_checkbox_error' => 'Musisz zaakceptować Politykę prywatności.',
        'privacy_checkbox_description' => 'Akceptacja Polityki prywatności.',
        'withdrawal_checkbox_enabled' => true,
        'withdrawal_checkbox_label' => 'Potwierdzam, że zostałem poinformowany o <a href="%s" target="_blank">prawie odstąpienia od umowy</a> w ciągu 14 dni.',
        'withdrawal_checkbox_error' => 'Musisz potwierdzić zapoznanie się z informacją o prawie odstąpienia.',
        'withdrawal_checkbox_description' => 'Potwierdzenie informacji o 14-dniowym prawie odstąpienia.',
        'digital_waiver_checkbox_enabled' => false,
        'digital_waiver_checkbox_label' => 'Wyrażam zgodę na rozpoczęcie dostarczania treści cyfrowych przed upływem terminu do odstąpienia od umowy i przyjmuję do wiadomości utratę prawa odstąpienia.',
        'digital_waiver_checkbox_error' => 'Musisz wyrazić zgodę na natychmiastowe dostarczenie treści cyfrowych.',
        'digital_waiver_checkbox_description' => 'Zrzeczenie się prawa odstąpienia dla treści cyfrowych.',
        'parcel_delivery_checkbox_enabled' => false,
        'parcel_delivery_checkbox_label' => 'Wyrażam zgodę na otrzymywanie powiadomień SMS/email o statusie dostawy przesyłki.',
        'parcel_delivery_checkbox_description' => 'Opcjonalna zgoda na powiadomienia o dostawie.',
        'review_reminder_checkbox_enabled' => false,
        'review_reminder_checkbox_label' => 'Wyrażam zgodę na otrzymanie przypomnienia o wystawieniu opinii drogą mailową po zakupie.',
        'review_reminder_checkbox_description' => 'Opcjonalna zgoda na przypomnienia o opinii.',
        'marketing_checkbox_enabled' => false,
        'marketing_checkbox_label' => 'Wyrażam zgodę na otrzymywanie komunikacji marketingowej i newslettera.',
        'marketing_checkbox_description' => 'Opcjonalna zgoda marketingowa.',
        'delayed_payment_enabled' => false,
    ],

    // Emails.
    'polski_emails' => [
        'attach_terms' => true,
        'attach_privacy' => false,
        'attach_withdrawal' => true,
    ],

    // Withdrawal.
    'polski_withdrawal' => [
        'button_text' => 'Odstąp od umowy',
        'form_title' => 'Wniosek o odstąpienie od umowy',
        'form_intro_text' => 'Składasz wniosek o odstąpienie dla zamówienia #{order_number} z dnia {order_date}.',
        'legal_notice_text' => 'Zgodnie z polskim prawem masz 14 dni na odstąpienie od umowy bez podawania przyczyny.',
        'items_heading' => 'Pozycje zamówienia',
        'column_product' => 'Produkt',
        'column_quantity' => 'Ilość',
        'column_price' => 'Cena',
        'exempt_notice_text' => '(Produkt wyłączony z prawa odstąpienia)',
        'reason_label' => 'Powód odstąpienia (opcjonalnie)',
        'submit_button_text' => 'Wyślij wniosek o odstąpienie',
        'invalid_nonce_text' => 'Ups, coś poszło nie tak po naszej stronie. Spróbuj ponownie, proszę!',
        'order_not_found_text' => 'Niestety, nie udało nam się znaleźć takiego zamówienia.',
        'permission_error_text' => 'Nie masz uprawnień do odstąpienia od tego zamówienia.',
        'success_text' => 'Twój wniosek o zwrot został przyjęty. Niedługo wyślemy Ci potwierdzenie na e-mail!',
        'not_eligible_text' => 'To zamówienie nie kwalifikuje się do odstąpienia.',
        'status_heading' => 'Wniosek o odstąpienie',
        'status_label' => 'Status',
        'submitted_label' => 'Złożono',
        'requested_order_note' => 'Klient złożył wniosek o odstąpienie od umowy.',
        'confirmed_order_note' => 'Wniosek o odstąpienie potwierdzony.',
        'status_date_format' => 'Y-m-d H:i',
        'email_subject' => 'Dobra wiadomość! Twój wniosek o zwrot, zamówienie #{order_number}, został pomyślnie potwierdzony.',
        'email_heading' => 'Odstąpienie potwierdzone',
        'email_greeting' => 'Dzień dobry {name},',
        'email_intro_text' => 'Twój wniosek o odstąpienie dla zamówienia #{order_number} został potwierdzony.',
        'email_reason_label' => 'Twój powód',
        'email_return_instruction' => 'Odeślij produkty na poniższy adres w ciągu 14 dni:',
        'email_additional_content' => 'Zwrot środków zostanie zrealizowany w ciągu 14 dni od daty otrzymania zwróconych produktów.',
    ],

    // Tax.
    'polski_taxes' => [
        'vat_notice_text' => 'w tym {rate}% VAT',
        'vat_exempt_notice' => 'Zwolniony z VAT na podstawie art. 113 ust. 1 ustawy o VAT',
    ],

    // Delivery times.
    'polski_delivery' => [
        'default_delivery_time' => '',
        'display_format' => 'Czas dostawy: {time}',
    ],

    // Double opt-in.
    'polski_doi' => [
        'enabled' => false,
        'cleanup_days' => 7,
        'login_blocked_text' => 'Twoje konto czeka na aktywację! Zerknij do swojej skrzynki e-mail i kliknij w przesłany przez nas link.',
        'invalid_link_text' => 'Nieprawidłowy link aktywacyjny.',
        'activation_success_text' => 'Wspaniale! Twoje konto jest już aktywowane. Możesz się teraz śmiało zalogować.',
        'email_subject' => 'Aktywuj swoje konto w {site_title}',
        'email_heading' => 'Potwierdź swój adres email',
        'email_greeting' => 'Cześć {name},',
        'email_intro_html' => 'Dziękujemy za założenie konta. Kliknij przycisk poniżej, aby aktywować konto:',
        'email_button_text' => 'Aktywuj konto',
        'email_link_intro' => 'Jeśli wolisz, skopiuj i wklej ten link do przeglądarki:',
        'email_intro_plain' => 'Dziękujemy za założenie konta. Odwiedź poniższy link, aby aktywować konto:',
        'additional_content' => 'Jeśli to nie Ty zakładałeś/-aś u nas konto, nie przejmuj się i po prostu wykasuj tę wiadomość.',
    ],

    // Request a quote.
    'polski_quote' => [
        'enabled' => false,
        'availability' => 'selected',
        'show_on_single' => true,
        'show_on_loop' => false,
        'allow_guest' => true,
        'replace_add_to_cart' => false,
        'hide_prices' => false,
        'button_text' => 'Zapytaj o wycenę',
        'modal_title' => 'Zapytaj o indywidualną wycenę',
        'intro_text' => 'Wypełnij krótki formularz, a wrócimy z wyceną dopasowaną do Twojego zamówienia.',
        'close_label' => 'Zamknij formularz wyceny',
        'login_required_text' => 'Zaloguj się, aby wysłać zapytanie ofertowe dla tego produktu.',
        'name_label' => 'Imię i nazwisko',
        'email_label' => 'Email',
        'phone_label' => 'Telefon',
        'company_label' => 'Firma',
        'nip_label' => 'NIP',
        'postcode_label' => 'Kod pocztowy',
        'quantity_label' => 'Ilość',
        'message_label' => 'Szczegóły zapytania',
        'message_placeholder' => 'Napisz czego potrzebujesz, jaki masz termin i jakie są założenia zamówienia.',
        'submit_text' => 'Wyślij zapytanie',
        'success_text' => 'Dziękujemy. Twoje zapytanie zostało wysłane, wrócimy z odpowiedzią tak szybko, jak to możliwe.',
        'price_placeholder_text' => 'Cena dostępna po wycenie',
        'invalid_contact_text' => 'Uzupełnij poprawnie imię i adres email.',
        'phone_required_text' => 'Podaj numer telefonu do kontaktu.',
        'company_required_text' => 'Podaj nazwę firmy.',
        'nip_required_text' => 'Podaj numer NIP.',
        'nip_invalid_text' => 'Podaj poprawny numer NIP.',
        'postcode_required_text' => 'Podaj kod pocztowy.',
        'privacy_required_text' => 'Musisz zaakceptować zgodę prywatności.',
        'minimum_quantity_text' => 'Minimalna ilość dla tego zapytania to {quantity}.',
        'save_error_text' => 'Nie udało się zapisać zapytania. Spróbuj ponownie.',
        'product_unavailable_text' => 'Nie udało się przygotować zapytania dla tego produktu.',
        'recipient_email' => '',
        'require_company' => true,
        'require_phone' => true,
        'require_nip' => false,
        'require_postcode' => false,
        'privacy_required' => true,
        'privacy_label' => 'Akceptuję politykę prywatności i zgadzam się na kontakt w sprawie wyceny.',
        'admin_email_subject' => 'Nowe zapytanie ofertowe - {product_name}',
        'customer_email_subject' => 'Potwierdzenie zapytania ofertowego - {product_name}',
        'customer_email_enabled' => true,
        'admin_page_title' => 'Zapytania ofertowe',
        'admin_success_notice' => 'Status zapytania został zaktualizowany.',
        'admin_filter_all_label' => 'Wszystkie',
        'admin_column_date' => 'Data',
        'admin_column_product' => 'Produkt',
        'admin_column_customer' => 'Klient',
        'admin_column_company' => 'Firma / NIP',
        'admin_column_quantity' => 'Ilość',
        'admin_column_status' => 'Status',
        'admin_column_actions' => 'Akcje',
        'admin_empty_text' => 'Brak zapytań ofertowych.',
        'admin_postcode_label' => 'Kod',
        'admin_date_format' => 'Y-m-d H:i',
    ],

    // Catalog mode.
    'polski_catalog' => [
        'enabled' => false,
        'availability' => 'selected',
        'audience' => 'guests_only',
        'selected_roles' => '',
        'hide_prices' => true,
        'hide_add_to_cart' => true,
        'replacement_mode' => 'quote',
        'cta_text' => 'Zapytaj o warunki handlowe',
        'login_cta_text' => 'Zaloguj się, aby zobaczyć ofertę',
        'custom_url' => '',
        'custom_url_target' => 'same_tab',
        'hidden_price_text' => 'Cena dostępna po zalogowaniu lub po kontakcie z obsługą.',
        'single_notice' => 'Produkt dostępny w trybie katalogowym. Skontaktuj się z nami, aby uzyskać warunki handlowe lub ofertę B2B.',
        'loop_notice' => 'Zobacz warunki handlowe',
        'single_both_hidden_text' => 'Ceny i zakup online są ukryte dla tego produktu.',
        'single_price_hidden_text' => 'Cena jest ukryta dla tego produktu.',
        'single_cart_hidden_text' => 'Zakup online jest wyłączony dla tego produktu.',
        'show_single_cta' => true,
        'show_loop_notice' => true,
        'show_single_notice' => true,
        'show_single_restriction_text' => true,
    ],

    // Ajax search.
    'polski_search' => [
        'enabled' => false,
        'min_chars' => 2,
        'limit' => 6,
        'debounce_ms' => 180,
        'show_submit_button' => true,
        'show_image' => true,
        'show_price' => true,
        'show_sku' => true,
        'show_view_all_link' => true,
        'search_sku' => true,
        'search_categories' => true,
        'include_out_of_stock' => false,
        'search_label' => 'Szukaj produktów',
        'results_label' => 'Wyniki wyszukiwania produktów',
        'sku_label' => 'SKU',
        'placeholder' => 'Szukaj produktów, kodów SKU lub kategorii',
        'submit_button_text' => 'Szukaj',
        'no_results_text' => 'Brak wyników dla podanego zapytania.',
        'view_all_text' => 'Zobacz wszystkie wyniki',
    ],

    // Brands.
    'polski_brand' => [
        'enabled' => false,
        'show_on_single' => true,
        'show_on_loop' => true,
        'label' => 'Marka',
        'show_label' => true,
        'separator' => ', ',
        'link_terms' => true,
    ],

    // Ajax filters.
    'polski_filters' => [
        'enabled' => false,
        'show_on_shop' => true,
        'show_title' => true,
        'show_categories' => true,
        'show_brands' => true,
        'show_price' => true,
        'show_stock' => true,
        'show_sale' => true,
        'show_attributes' => true,
        'max_attribute_taxonomies' => 4,
        'category_label' => 'Kategoria',
        'category_all_text' => 'Wszystkie',
        'brand_label' => 'Marka',
        'brand_all_text' => 'Wszystkie',
        'min_price_label' => 'Cena od',
        'max_price_label' => 'Cena do',
        'stock_label' => 'Dostępność',
        'stock_any_text' => 'Dowolna',
        'stock_instock_text' => 'Dostępne od ręki',
        'sale_label' => 'Promocje',
        'attribute_any_text' => 'Dowolny',
        'show_reset_link' => true,
        'submit_text' => 'Filtruj',
        'reset_text' => 'Wyczyść filtry',
        'title' => 'Filtry produktów',
    ],

    // Wishlist.
    'polski_wishlist' => [
        'enabled' => false,
        'allow_guests' => true,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_in_account' => true,
        'show_title' => true,
        'show_product_image' => true,
        'show_product_name' => true,
        'show_price' => true,
        'show_add_to_cart' => true,
        'show_remove_button' => true,
        'grid_columns' => 4,
        'account_label' => 'Ulubione',
        'button_add_text' => 'Dodaj do ulubionych',
        'button_remove_text' => 'Usuń z ulubionych',
        'account_intro_text' => '',
        'login_required_text' => 'Zaloguj się, aby korzystać z listy życzeń.',
        'product_not_found_text' => 'Nie znaleziono produktu.',
        'empty_text' => 'Lista ulubionych jest pusta.',
        'title' => 'Twoje ulubione produkty',
    ],

    // Compare.
    'polski_compare' => [
        'enabled' => false,
        'allow_guests' => true,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_in_account' => true,
        'show_product_image' => true,
        'show_add_to_cart' => true,
        'show_remove_button' => true,
        'account_label' => 'Porównanie',
        'button_add_text' => 'Dodaj do porównania',
        'button_remove_text' => 'Usuń z porównania',
        'login_required_text' => 'Zaloguj się, aby korzystać z porównania produktów.',
        'product_not_found_text' => 'Nie znaleziono produktu.',
        'limit_notice_text' => 'Możesz porównać maksymalnie {limit} produkty jednocześnie. Najstarszy wpis został zastąpiony automatycznie.',
        'clear_error_text' => 'Nie możesz wyczyścić porównania.',
        'intro_text' => '',
        'empty_text' => 'Lista porównawcza jest pusta.',
        'title' => 'Porównanie produktów',
        'compare_link_text' => 'Porównaj produkty',
        'clear_text' => 'Wyczyść porównanie',
        'feature_label' => 'Cecha',
        'differences_toggle_text' => 'Pokazuj tylko różnice',
        'price_label' => 'Cena',
        'unit_price_label' => 'Cena jednostkowa',
        'sku_label' => 'SKU',
        'availability_label' => 'Dostępność',
        'delivery_time_label' => 'Czas dostawy',
        'brand_label' => 'Marka',
        'manufacturer_label' => 'Producent',
        'gtin_label' => 'GTIN / EAN',
        'description_label' => 'Krótki opis',
        'max_items' => 4,
        'highlight_differences' => true,
        'show_only_differences' => false,
        'show_description' => true,
        'show_attributes' => true,
    ],

    // Quick view.
    'polski_quick_view' => [
        'enabled' => false,
        'show_on_loop' => true,
        'button_text' => 'Szybki podgląd',
        'modal_title' => 'Szybki podgląd produktu',
        'close_label' => 'Zamknij',
        'loading_text' => 'Ładowanie produktu...',
        'error_text' => 'Nie udało się wczytać podglądu produktu.',
        'product_not_found_text' => 'Nie znaleziono produktu.',
        'sku_label' => 'SKU',
        'show_close_button' => true,
        'show_modal_label' => true,
        'show_title' => true,
        'show_image' => true,
        'show_gallery' => true,
        'show_price' => true,
        'show_unit_price' => true,
        'show_sku' => true,
        'show_delivery_time' => true,
        'show_brand' => true,
        'show_manufacturer' => true,
        'show_short_description' => true,
        'show_add_to_cart' => true,
        'show_view_product_link' => true,
        'view_product_text' => 'Zobacz pełną kartę produktu',
        'view_product_target' => 'same_tab',
        'show_backdrop_close' => true,
    ],

    // Frequently bought together.
    'polski_fbt' => [
        'enabled' => false,
        'show_on_single' => true,
        'title' => 'Często kupowane razem',
        'intro_text' => 'Zaproponuj klientowi gotowy zestaw produktów komplementarnych i dodaj całość do koszyka jednym kliknięciem.',
        'button_text' => 'Dodaj zestaw do koszyka',
        'empty_text' => 'Brak skonfigurowanych produktów do zestawu.',
        'show_title' => true,
        'show_price' => true,
        'show_empty_state' => false,
        'total_label' => 'Łącznie:',
        'success_text' => 'Dodano {count} produktów z zestawu do koszyka.',
        'show_total' => true,
        'show_images' => true,
        'show_checkboxes' => true,
        'preselect_products' => true,
        'show_short_description' => false,
        'max_related_products' => 4,
    ],

    // Badges.
    'polski_badges' => [
        'enabled' => false,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_manual_badge' => true,
        'manual_badge_style' => 'accent',
        'show_secondary_badge' => true,
        'secondary_badge_style' => 'neutral',
        'show_sale_badge' => true,
        'show_new_badge' => true,
        'newness_days' => 30,
        'show_low_stock_badge' => true,
        'low_stock_threshold' => 3,
        'show_bestseller_badge' => true,
        'bestseller_threshold' => 25,
        'shape' => 'pill',
        'uppercase' => false,
        'max_badges_single' => 4,
        'max_badges_loop' => 3,
        'sale_badge_text' => 'Promocja',
        'new_badge_text' => 'Nowość',
        'low_stock_badge_text' => 'Ostatnie sztuki',
        'bestseller_badge_text' => 'Bestseller',
    ],

    // Tab manager.
    'polski_tabs' => [
        'enabled' => false,
        'enable_global_shipping_tab' => false,
        'shipping_tab_title' => 'Dostawa i płatność',
        'shipping_tab_content' => '',
        'shipping_tab_priority' => 47,
        'enable_global_returns_tab' => false,
        'returns_tab_title' => 'Zwroty i reklamacje',
        'returns_tab_content' => '',
        'returns_tab_priority' => 48,
        'enable_product_tab_1' => true,
        'product_tab_1_priority' => 45,
        'enable_product_tab_2' => true,
        'product_tab_2_priority' => 46,
    ],

    // Featured video.
    'polski_featured_video' => [
        'enabled' => false,
        'show_on_single' => true,
        'position' => 'after_gallery',
        'title' => 'Zobacz produkt w użyciu',
        'intro_text' => '',
        'autoplay' => false,
        'show_title' => true,
        'show_intro' => false,
    ],

    // Gallery and zoom.
    'polski_gallery_zoom' => [
        'enabled' => false,
        'enable_zoom' => true,
        'zoom_scale' => 1.45,
        'enable_lightbox' => true,
        'dialog_label' => 'Podgląd galerii produktu',
        'close_label' => 'Zamknij podgląd galerii',
        'show_backdrop_close' => true,
    ],

    // Product slider.
    'polski_slider' => [
        'enabled' => false,
        'show_on_single' => true,
        'source' => 'related',
        'title' => 'Polecane produkty',
        'limit' => 8,
        'show_title' => true,
        'show_intro_text' => false,
        'intro_text' => '',
        'show_image' => true,
        'show_price' => true,
        'show_name' => true,
        'show_add_to_cart' => true,
        'show_view_all_link' => false,
        'show_empty_state' => false,
        'empty_text' => 'Brak produktów do wyświetlenia w tej sekcji.',
        'view_all_text' => 'Zobacz wszystkie produkty',
        'view_all_target' => 'same_tab',
    ],

    // Pre-order.
    'polski_preorder' => [
        'enabled' => false,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_notice' => true,
        'button_text' => 'Zamów w przedsprzedaży',
        'availability_text' => 'Przedsprzedaż, wysyłka od {date}',
        'notice_text' => 'Ten produkt jest dostępny w przedsprzedaży. Zamów teraz, a wysyłkę zrealizujemy od {date}.',
        'notice_title' => 'Przedsprzedaż',
        'show_notice_title' => false,
        'date_format' => 'd.m.Y',
        'allow_mixed_cart' => true,
        'mixed_cart_error_text' => 'Produkty z przedsprzedaży nie mogą być łączone z innymi produktami w tym samym koszyku.',
    ],

    // Waitlist.
    'polski_waitlist' => [
        'enabled' => false,
        'show_on_single' => true,
        'allow_guests' => true,
        'title' => 'Powiadom mnie o dostępności',
        'show_title' => true,
        'intro_text' => 'Zostaw adres email, a damy znać, gdy produkt wróci na stan.',
        'show_intro' => true,
        'email_label' => 'Adres email',
        'email_placeholder' => 'Twój adres email',
        'button_text' => 'Powiadom mnie',
        'success_text' => 'Dziękujemy. Zapisaliśmy Cię na listę oczekujących.',
        'privacy_label' => 'Akceptuję kontakt email w sprawie dostępności tego produktu.',
        'product_not_found_text' => 'Nie znaleziono produktu.',
        'disabled_text' => 'Lista oczekujących jest niedostępna dla tego produktu.',
        'invalid_email_text' => 'Podaj poprawny adres email.',
        'privacy_error_text' => 'Musisz zaakceptować zgodę na kontakt email.',
        'login_required_text' => 'Zaloguj się, aby zapisać się na listę oczekujących.',
        'notify_subject' => 'Produkt ponownie dostępny - {product_name}',
        'notify_intro_text' => 'Produkt {product_name} jest ponownie dostępny.',
        'notify_outro_text' => 'Jeśli nie chcesz już otrzymywać takich wiadomości, po prostu zignoruj ten email.',
    ],

    // Product add-ons.
    'polski_addons' => [
        'enabled' => false,
        'show_on_single' => true,
        'section_title' => 'Dodatki do produktu',
        'section_intro' => 'Skonfiguruj dodatki i usługi powiązane z tym produktem.',
        'show_price_inline' => true,
        'show_descriptions' => true,
        'field_style' => 'boxed',
        'required_badge_text' => 'Wymagane',
        'optional_badge_text' => 'Opcjonalne',
        'select_placeholder' => 'Wybierz opcję',
        'text_placeholder' => 'Wpisz wartość',
        'textarea_placeholder' => 'Wpisz szczegóły',
        'textarea_rows' => 3,
        'price_prefix' => '+',
    ],

    // Product bundles.
    'polski_bundles' => [
        'enabled' => false,
        'show_on_single' => true,
        'title' => 'Kup w zestawie',
        'intro_text' => 'Połącz produkt główny z akcesoriami i kup całość w jednym pakiecie.',
        'button_text' => 'Dodaj zestaw do koszyka',
        'selection_required_text' => 'Wybierz przynajmniej jeden dodatkowy produkt do zestawu.',
        'success_text' => 'Dodano zestaw do koszyka.',
        'show_total' => true,
        'show_quantities' => true,
        'bundle_total_label' => 'Cena zestawu',
        'included_label' => 'w zestawie',
        'quantity_format' => 'x {quantity}',
        'discount_label' => 'Oszczędzasz',
    ],

    // Gift cards.
    'polski_gift_cards' => [
        'enabled' => false,
        'show_on_single' => true,
        'show_in_account' => true,
        'account_label' => 'Karty podarunkowe',
        'title' => 'Karta podarunkowa',
        'product_form_title' => 'Dane karty podarunkowej',
        'show_product_form_title' => true,
        'recipient_required_text' => 'Uzupełnij dane nadawcy i odbiorcy karty podarunkowej.',
        'recipient_email_error_text' => 'Podaj poprawny adres email odbiorcy.',
        'amount_error_text' => 'Wybierz poprawną kwotę karty podarunkowej.',
        'recipient_name_label' => 'Imię odbiorcy',
        'recipient_email_label' => 'Email odbiorcy',
        'sender_name_label' => 'Imię nadawcy',
        'amount_label' => 'Kwota',
        'custom_amount_label' => 'Własna kwota',
        'message_label' => 'Wiadomość',
        'code_placeholder' => 'Wpisz kod karty',
        'invalid_code_text' => 'Podany kod karty podarunkowej jest nieprawidłowy lub nieaktywny.',
        'applied_code_text' => 'Kod karty podarunkowej został zastosowany.',
        'removed_code_text' => 'Usunięto kartę podarunkową z koszyka.',
        'account_title' => 'Karty podarunkowe',
        'show_account_title' => true,
        'account_intro_text' => '',
        'empty_text' => 'Brak kart podarunkowych przypisanych do Twojego konta.',
        'column_code' => 'Kod',
        'column_balance' => 'Saldo',
        'column_recipient' => 'Odbiorca',
        'column_status' => 'Status',
        'column_expiry' => 'Ważna do',
        'show_recipient_email_in_account' => true,
        'show_balance_column' => true,
        'show_recipient_column' => true,
        'show_status_column' => true,
        'show_expiry_column' => true,
        'date_format' => 'd.m.Y',
        'status_active' => 'Aktywna',
        'status_used' => 'Wykorzystana',
        'status_expired' => 'Wygasła',
        'fee_label' => 'Karta podarunkowa {code}',
        'redeem_title' => 'Masz kartę podarunkową?',
        'show_redeem_title' => true,
        'redeem_button_text' => 'Zastosuj kod',
        'remove_button_text' => 'Usuń kod',
        'code_prefix' => 'SP',
        'expiry_days' => 365,
        'allow_custom_amount' => true,
        'default_amounts' => '50,100,200',
        'min_amount' => 20,
        'max_amount' => 1000,
        'email_subject' => 'Otrzymujesz kartę podarunkową - {code}',
        'email_heading' => 'Ktoś wysłał Ci kartę podarunkową do sklepu',
    ],

    // Subscriptions.
    'polski_subscriptions' => [
        'enabled' => false,
        'show_on_single' => true,
        'show_in_account' => true,
        'account_label' => 'Subskrypcje',
        'section_title' => 'Subskrypcja produktu',
        'show_section_title' => true,
        'section_intro' => 'Kupuj cyklicznie bez ponownego składania zamówienia.',
        'show_section_intro' => true,
        'subscription_label' => 'Subskrypcja',
        'subscription_cycle_format' => 'co {count} {period}',
        'signup_fee_label' => 'Opłata startowa: {price}',
        'trial_label' => 'Okres próbny: {duration}',
        'trial_value_format' => '{days} {period}',
        'renewal_notice' => 'Kolejne odnowienie: co {interval} {period}.',
        'period_day_singular' => 'dzień',
        'period_day_plural' => 'dni',
        'period_week_singular' => 'tydzień',
        'period_week_plural' => 'tygodnie',
        'period_month_singular' => 'miesiąc',
        'period_month_plural' => 'miesiące',
        'period_year_singular' => 'rok',
        'period_year_plural' => 'lata',
        'allow_cancellation' => true,
        'account_title' => 'Subskrypcje',
        'show_account_title' => true,
        'account_intro_text' => '',
        'empty_text' => 'Brak aktywnych subskrypcji.',
        'column_product' => 'Produkt',
        'column_cycle' => 'Cykl',
        'column_amount' => 'Kwota',
        'column_status' => 'Status',
        'column_next_payment' => 'Następne odnowienie',
        'column_actions' => 'Akcje',
        'show_product_column' => true,
        'show_cycle_column' => true,
        'show_amount_column' => true,
        'show_status_column' => true,
        'show_next_payment_column' => true,
        'show_actions_column' => true,
        'date_format' => 'd.m.Y',
        'cancel_button_text' => 'Anuluj',
        'reactivate_button_text' => 'Wznów',
        'cancel_success_text' => 'Subskrypcja została anulowana.',
        'reactivate_success_text' => 'Subskrypcja została ponownie aktywowana.',
        'status_active' => 'Aktywna',
        'status_trial' => 'Okres próbny',
        'status_cancelled' => 'Anulowana',
        'status_completed' => 'Zakończona',
        'reminder_days' => 3,
        'renewal_subject' => 'Nowe odnowienie subskrypcji - {product_name}',
        'reminder_subject' => 'Zbliża się odnowienie subskrypcji - {product_name}',
        'reminder_intro_text' => 'Subskrypcja produktu {product_name} odnowi się {date}.',
        'reminder_amount_label' => 'Kwota odnowienia: {amount}',
        'renewal_intro_text' => 'Utworzyliśmy nowe zamówienie odnowieniowe dla subskrypcji produktu {product_name}.',
        'renewal_amount_label' => 'Kwota do opłacenia: {amount}',
    ],

    // Infinite scrolling.
    'polski_infinite_scroll' => [
        'enabled' => false,
        'mode' => 'button',
        'button_text' => 'Załaduj więcej produktów',
        'loading_text' => 'Ładowanie produktów...',
        'error_text' => 'Nie udało się załadować kolejnych produktów.',
        'end_text' => 'To już wszystkie produkty.',
        'show_on_shop' => true,
        'show_on_taxonomies' => true,
        'auto_after_pages' => 0,
        'show_status' => true,
        'show_button_in_auto_mode' => false,
    ],

    // Popup.
    'polski_popup' => [
        'enabled' => false,
        'title' => 'Masz pytanie o produkt lub warunki handlowe?',
        'content' => 'Skontaktuj się z nami, jeśli chcesz dostać ofertę B2B, rabat dla hurtu albo pomoc z doborem produktu.',
        'cta_text' => 'Przejdź do kontaktu',
        'show_title' => true,
        'show_close_button' => true,
        'close_label' => 'Zamknij popup',
        'dialog_label' => 'Popup promocyjny',
        'cta_url' => '',
        'fallback_cta_url' => 'account',
        'show_cta' => true,
        'cta_target' => 'same_tab',
        'show_backdrop_close' => true,
        'show_on_home' => true,
        'show_on_shop' => true,
        'show_on_product' => false,
        'show_on_cart' => false,
        'show_on_checkout' => false,
        'delay_seconds' => 4,
        'frequency_days' => 7,
    ],

    // Affiliates.
    'polski_affiliates' => [
        'enabled' => false,
        'show_in_account' => true,
        'show_dashboard_title' => true,
        'show_dashboard_intro' => true,
        'show_referral_link' => true,
        'show_stats' => true,
        'show_table' => true,
        'show_order_column' => true,
        'show_customer_column' => true,
        'show_value_column' => true,
        'show_commission_column' => true,
        'show_status_column' => true,
        'show_date_column' => true,
        'account_label' => 'Program partnerski',
        'dashboard_title' => 'Panel partnera',
        'dashboard_intro_text' => '',
        'login_required_text' => 'Zaloguj się, aby korzystać z programu partnerskiego.',
        'referral_link_label' => 'Twój link partnerski',
        'stats_referrals_label' => 'Polecenia: {count}',
        'stats_revenue_label' => 'Sprzedaż: {amount}',
        'stats_commission_label' => 'Prowizja: {amount}',
        'empty_text' => 'Brak poleceń przypisanych do Twojego konta.',
        'column_order' => 'Zamówienie',
        'column_customer' => 'Klient',
        'column_value' => 'Wartość',
        'column_commission' => 'Prowizja',
        'column_status' => 'Status',
        'column_date' => 'Data',
        'order_prefix' => '#',
        'date_format' => 'd.m.Y',
        'referral_param' => 'poleca',
        'cookie_days' => 30,
        'commission_percent' => 5,
        'minimum_order_total' => 0,
        'pending_statuses' => 'processing,completed',
    ],

    // Food module.
    'polski_food' => [
        'enabled' => false,
        'show_ingredients' => true,
        'show_allergens' => true,
        'show_nutrients' => true,
        'show_nutri_score' => true,
        'show_alcohol' => true,
        'show_origin' => true,
        'show_distributor' => true,
        'show_net_filling' => true,
        'ingredients_label' => 'Składniki',
        'allergens_label' => 'Alergeny',
        'nutrients_caption_prefix' => 'Wartości odżywcze na',
        'nutrients_column_name' => 'Składnik odżywczy',
        'nutrients_column_value' => 'Wartość',
        'nutrients_reference_unit' => '100 g',
        'nutri_score_label' => 'Nutri-Score',
        'alcohol_label' => 'Zawartość alkoholu',
        'alcohol_suffix' => '% vol.',
        'origin_label' => 'Kraj pochodzenia',
        'distributor_label' => 'Dystrybutor',
        'net_filling_label' => 'Zawartość netto',
    ],
];
