<?php

declare(strict_types=1);

defined('ABSPATH') || exit;
/**
 * Default settings for the Polish market.
 *
 * These are applied on first activation. Each key maps to a WordPress option.
 * Values are only set if the option does not already exist.
 */
return [
    // General.
    'polski_general' => [
        'small_business' => false,
        'remove_data_on_uninstall' => false,
        'bdo_number' => '',
        'dispute_resolution_enabled' => true,
        'dispute_resolution_text' => __('ODR platform: https://ec.europa.eu/consumers/odr', 'polski'),
        'admin_pages_generated_notice' => __('Done. We have generated draft legal pages for you. Review them, adjust them to your shop and publish them.', 'polski'),
        'admin_modules_saved_notice' => __('Modules saved.', 'polski'),
        'admin_setup_note_title' => __('Set up Polski for your shop', 'polski'),
        'admin_setup_note_content' => __('Your shop is nearly ready. Review the modules, set up the legal pages and finish the configuration in the Polski panel.', 'polski'),
        'admin_setup_note_button' => __('Open the Polski configuration', 'polski'),
        'admin_status_active' => __('Switched on', 'polski'),
        'admin_status_inactive' => __('Switched off', 'polski'),
        'admin_status_unconfigured' => __('Not configured', 'polski'),
        'admin_legal_pages_card_title' => __('Legal pages', 'polski'),
        'admin_legal_pages_card_progress' => __('You have completed {done} of {total} steps. Well done.', 'polski'),
        'admin_vat_card_title' => __('Tax display', 'polski'),
        'admin_vat_small_business_text' => __('Small business exemption (Article 113)', 'polski'),
        'admin_vat_standard_text' => __('Standard VAT', 'polski'),
        'admin_doi_card_title' => __('Double opt-in', 'polski'),
        'admin_legal_pages_section_title' => __('Legal pages', 'polski'),
        'admin_legal_pages_table_page' => __('Page', 'polski'),
        'admin_legal_pages_table_status' => __('Status', 'polski'),
        'admin_legal_pages_published' => __('Page published', 'polski'),
        'admin_legal_pages_draft' => __('Draft', 'polski'),
        'admin_legal_pages_missing' => __('Not created', 'polski'),
        'admin_edit_button_text' => __('Edit', 'polski'),
        'admin_generate_pages_empty_text' => __('No legal pages have been created yet. Generate them to get started.', 'polski'),
        'admin_generate_pages_button_text' => __('Generate the legal pages', 'polski'),
        'admin_next_steps_title' => __('Next steps', 'polski'),
        'admin_next_steps_publish_pages' => __('Publish your legal pages: Terms and conditions, Privacy policy, Right of withdrawal and Complaints.', 'polski'),
        /* translators: %s is the WooCommerce tax settings URL. */
        'admin_next_steps_tax' => __('Set up the <a href="%s">VAT rates</a> in WooCommerce for the Polish market: 23%%, 8%%, 5%% and 0%%.', 'polski'),
        /* translators: %s is the WooCommerce shipping zones URL. */
        'admin_next_steps_shipping' => __('Set up <a href="%s">shipping zones</a> for deliveries in Poland.', 'polski'),
        /* translators: %s is the WooCommerce product edit URL for Polski product data. */
        'admin_next_steps_products' => __('Fill in the product data, adding unit prices and delivery times in the <a href="%s">Polski tab</a> of every product.', 'polski'),
        /* translators: %s is the WooCommerce checkout page URL. */
        'admin_next_steps_checkout' => __('Test the checkout: add a product to the cart and check the legal checkboxes and the button wording on the <a href="%s">checkout page</a>.', 'polski'),
        'admin_omnibus_plugin_detected_text' => __('detected, data is being synchronised', 'polski'),
        'admin_omnibus_plugin_missing_text' => __('not installed', 'polski'),
        'admin_omnibus_no_external_text' => __('No external Omnibus plugin is installed. Polski uses its own price history.', 'polski'),
        'admin_omnibus_external_active_text' => __('An external plugin was detected. Polski uses its data instead of its own price history.', 'polski'),
        'admin_integration_detected_text' => __('detected, integration active', 'polski'),
        'admin_integration_missing_text' => __('not detected', 'polski'),
        'admin_checkout_toolkit_no_external_text' => __('No supported checkout or cookie extension was detected. Polski works on its own.', 'polski'),
        'admin_checkout_toolkit_external_active_text' => __('A supported checkout, cookie or product data extension was detected. Polski can adapt to what is active.', 'polski'),
        'admin_payment_no_external_text' => __('No supported Polish payment gateway was detected. Polski uses its own checkout settings with no further integration.', 'polski'),
        'admin_payment_external_active_text' => __('Polish payment gateways were detected. Polski can adapt the checkout and the legal notices to the active methods.', 'polski'),
    ],

    // Price display.
    'polski_prices' => [
        'tax_display_mode' => 'brutto',
        'unit_price_enabled' => true,
        'unit_price_text' => __('{price} / {unit}', 'polski'),
        'shipping_costs_notice_enabled' => true,
        'shipping_costs_text' => __('plus shipping', 'polski'),
        'from_price_enabled' => true,
        'from_price_text' => __('from {price}', 'polski'),
    ],

    // Omnibus directive.
    'polski_omnibus' => [
        'enabled' => true,
        'days' => 30,
        'display_text' => __('Lowest price in the last {days} days: {price}', 'polski'),
        'display_on_sale_only' => true,
        'prune_after_days' => 90,
    ],

    // Review request emails.
    'polski_review_requests' => [
        'delay_days' => 7,
        'email_subject' => __('How was your order? Leave a review', 'polski'),
        'email_intro' => __('Hello {first_name}, thank you for your recent order. We would be grateful for your review.', 'polski'),
        'review_cta_text' => __('Leave a review', 'polski'),
        'optout_link_text' => __('Unsubscribe from review requests', 'polski'),
        'optout_success_text' => __('We will not send you review requests any more.', 'polski'),
    ],

    // Minimum order rules.
    'polski_minimum_order' => [
        'min_value' => 0,
        'min_quantity' => 0,
        'exclude_sale_items' => false,
        'min_value_message' => __('The minimum order value is {min_value}. Your cart is currently {current_value}.', 'polski'),
        'min_quantity_message' => __('The minimum number of items per order is {min_quantity}. You currently have {current_quantity}.', 'polski'),
    ],

    // Checkout.
    'polski_checkout' => [
        'order_button_text' => __('Order with an obligation to pay', 'polski'),
        'terms_checkbox_enabled' => true,
        /* translators: %s is the terms and conditions page URL. */
        'terms_checkbox_label' => __('I have read and accept the <a href="%s" target="_blank">terms and conditions</a>.', 'polski'),
        'terms_checkbox_error' => __('You have to accept the terms and conditions to place an order.', 'polski'),
        'terms_checkbox_description' => __('Terms and conditions accepted.', 'polski'),
        'privacy_checkbox_enabled' => true,
        /* translators: %s is the privacy policy page URL. */
        'privacy_checkbox_label' => __('I have read and accept the <a href="%s" target="_blank">privacy policy</a>.', 'polski'),
        'privacy_checkbox_error' => __('You have to accept the privacy policy.', 'polski'),
        'privacy_checkbox_description' => __('Privacy policy accepted.', 'polski'),
        'withdrawal_checkbox_enabled' => true,
        /* translators: %s is the withdrawal information page URL. */
        'withdrawal_checkbox_label' => __('I confirm that I have been informed of the <a href="%s" target="_blank">right of withdrawal</a> within 14 days.', 'polski'),
        'withdrawal_checkbox_error' => __('You have to confirm that you have read the information on the right of withdrawal.', 'polski'),
        'withdrawal_checkbox_description' => __('Information on the 14 day right of withdrawal acknowledged.', 'polski'),
        'digital_waiver_checkbox_enabled' => false,
        'digital_waiver_checkbox_label' => __('I consent to the supply of digital content beginning before the withdrawal period ends and I acknowledge that I thereby lose my right of withdrawal.', 'polski'),
        'digital_waiver_checkbox_error' => __('You have to consent to the immediate supply of digital content.', 'polski'),
        'digital_waiver_checkbox_description' => __('Right of withdrawal waived for digital content.', 'polski'),
        'parcel_delivery_checkbox_enabled' => false,
        'parcel_delivery_checkbox_label' => __('I consent to receiving SMS and email notifications about the delivery status of my parcel.', 'polski'),
        'parcel_delivery_checkbox_description' => __('Optional consent to delivery notifications.', 'polski'),
        'review_reminder_checkbox_enabled' => false,
        'review_reminder_checkbox_label' => __('I consent to receiving an email reminder to leave a review after my purchase.', 'polski'),
        'review_reminder_checkbox_description' => __('Optional consent to review reminders.', 'polski'),
        'marketing_checkbox_enabled' => false,
        'marketing_checkbox_label' => __('I consent to receiving marketing communication and the newsletter.', 'polski'),
        'marketing_checkbox_description' => __('Optional marketing consent.', 'polski'),
    ],

    // Emails.
    'polski_emails' => [
        'attach_terms' => true,
        'attach_privacy' => false,
        'attach_withdrawal' => true,
    ],

    // Withdrawal.
    'polski_withdrawal' => [
        'button_text' => __('Withdraw from the contract', 'polski'),
        'form_title' => __('Withdrawal declaration', 'polski'),
        'form_intro_text' => __('This refers to order #{order_number} placed on {order_date}.', 'polski'),
        'legal_notice_text' => __('Under Polish consumer law you have the right to withdraw from the contract within 14 days without giving a reason.', 'polski'),
        'items_heading' => __('Items in the order', 'polski'),
        'column_product' => __('Product', 'polski'),
        'column_quantity' => __('Quantity', 'polski'),
        'column_price' => __('Price', 'polski'),
        'exempt_notice_text' => __('(This product is excluded from the right of withdrawal)', 'polski'),
        'reason_label' => __('Reason for withdrawal (optional)', 'polski'),
        'submit_button_text' => __('Send the withdrawal declaration', 'polski'),
        'invalid_nonce_text' => __('Something went wrong on our side. Please try again.', 'polski'),
        'order_not_found_text' => __('We could not find that order.', 'polski'),
        'permission_error_text' => __('You are not allowed to withdraw from this order.', 'polski'),
        'success_text' => __('Your withdrawal declaration has been accepted. We will send a confirmation email shortly.', 'polski'),
        'not_eligible_text' => __('This order does not qualify for withdrawal.', 'polski'),
        'status_heading' => __('Withdrawal request', 'polski'),
        'status_label' => __('Status', 'polski'),
        'submitted_label' => __('Submitted', 'polski'),
        'requested_order_note' => __('The customer has filed a withdrawal declaration.', 'polski'),
        'confirmed_order_note' => __('The withdrawal declaration has been confirmed.', 'polski'),
        'status_date_format' => 'Y-m-d H:i',
        'email_subject' => __('Confirmation of the withdrawal declaration for order #{order_number}', 'polski'),
        'email_heading' => __('Withdrawal confirmed', 'polski'),
        'email_greeting' => __('Hi {name},', 'polski'),
        'email_intro_text' => __('Your withdrawal from the contract for order #{order_number} has been confirmed.', 'polski'),
        'email_reason_label' => __('Your reason', 'polski'),
        'email_return_instruction' => __('Please return the goods to the address above within 14 days:', 'polski'),
        'email_additional_content' => __('You will be refunded within 14 days of us receiving the returned goods.', 'polski'),
    ],

    // Tax.
    'polski_taxes' => [
        'vat_notice_text' => __('incl. {rate}% VAT', 'polski'),
        'vat_exempt_notice' => __('VAT exempt under Article 113(1) of the Polish VAT Act', 'polski'),
    ],

    // Delivery times.
    'polski_delivery' => [
        'default_delivery_time' => '',
        'display_format' => __('Delivery time: {time}', 'polski'),
        'show_in_loop' => false,
    ],

    // Double opt-in.
    'polski_doi' => [
        'enabled' => false,
        'cleanup_days' => 7,
        'login_blocked_text' => __('Your account is waiting to be activated. Check your inbox and click the link we sent you.', 'polski'),
        'invalid_link_text' => __('Invalid activation link.', 'polski'),
        'activation_success_text' => __('Your account is now active. You can log in.', 'polski'),
        'email_subject' => __('Activate your account at {site_title}', 'polski'),
        'email_heading' => __('Confirm your email address', 'polski'),
        'email_greeting' => __('Hi {name},', 'polski'),
        'email_intro_html' => __('Thank you for creating an account. Click the button below to activate it:', 'polski'),
        'email_button_text' => __('Activate the account', 'polski'),
        'email_link_intro' => __('If you prefer, copy this link into your browser:', 'polski'),
        'email_intro_plain' => __('Thank you for creating an account. Open the link below to activate it:', 'polski'),
        'additional_content' => __('If you did not create an account with us, simply delete this message.', 'polski'),
    ],

    // Request a quote.
    'polski_quote' => [
        'enabled' => false,
        'availability' => 'selected',
        'show_on_single' => true,
        'show_on_loop' => false,
        'allow_guest' => true,
        'replace_add_to_cart' => false,
        'hide_prices' => false,
        'button_text' => __('Request a quote', 'polski'),
        'modal_title' => __('Request a custom quote', 'polski'),
        'intro_text' => __('Fill in the short form and we will come back with a quote for your order.', 'polski'),
        'close_label' => __('Close the quote form', 'polski'),
        'login_required_text' => __('Log in to request a quote for this product.', 'polski'),
        'name_label' => __('Full name', 'polski'),
        'email_label' => __('Email', 'polski'),
        'phone_label' => __('Phone', 'polski'),
        'company_label' => __('Company', 'polski'),
        'nip_label' => __('NIP', 'polski'),
        'postcode_label' => __('Postcode', 'polski'),
        'quantity_label' => __('Quantity', 'polski'),
        'message_label' => __('Request details', 'polski'),
        'message_placeholder' => __('Tell us what you need, when you need it and what the order involves.', 'polski'),
        'submit_text' => __('Send the request', 'polski'),
        'success_text' => __('Thank you. Your request has been sent and we will reply as soon as we can.', 'polski'),
        'price_placeholder_text' => __('Price available on request', 'polski'),
        'invalid_contact_text' => __('Enter a valid name and email address.', 'polski'),
        'phone_required_text' => __('Enter a contact phone number.', 'polski'),
        'company_required_text' => __('Enter the company name.', 'polski'),
        'nip_required_text' => __('Enter the VAT ID (NIP).', 'polski'),
        'nip_invalid_text' => __('Enter a valid VAT ID (NIP).', 'polski'),
        'postcode_required_text' => __('Enter the postcode.', 'polski'),
        'privacy_required_text' => __('You have to accept the privacy consent.', 'polski'),
        'minimum_quantity_text' => __('The minimum quantity for this request is {quantity}.', 'polski'),
        'save_error_text' => __('The request could not be saved. Please try again.', 'polski'),
        'product_unavailable_text' => __('The request could not be prepared for this product.', 'polski'),
        'recipient_email' => '',
        'require_company' => true,
        'require_phone' => true,
        'require_nip' => false,
        'require_postcode' => false,
        'privacy_required' => true,
        'privacy_label' => __('I accept the privacy policy and agree to be contacted about the quote.', 'polski'),
        'admin_email_subject' => __('New quote request: {product_name}', 'polski'),
        'customer_email_subject' => __('Quote request confirmation: {product_name}', 'polski'),
        'customer_email_enabled' => true,
        'admin_page_title' => __('Quote requests', 'polski'),
        'admin_success_notice' => __('The request status has been updated.', 'polski'),
        'admin_filter_all_label' => __('All', 'polski'),
        'admin_column_date' => __('Date', 'polski'),
        'admin_column_product' => __('Product', 'polski'),
        'admin_column_customer' => __('Customer', 'polski'),
        'admin_column_company' => __('Company / VAT ID', 'polski'),
        'admin_column_quantity' => __('Quantity', 'polski'),
        'admin_column_status' => __('Status', 'polski'),
        'admin_column_actions' => __('Actions', 'polski'),
        'admin_empty_text' => __('No quote requests.', 'polski'),
        'admin_postcode_label' => __('Code', 'polski'),
        'admin_date_format' => 'Y-m-d H:i',
    ],

    // Catalog mode.
    'polski_catalog' => [
        'enabled' => false,
        'availability' => 'selected',
        'audience' => 'guests_only',
        'selected_roles' => '',
        'hide_prices' => true,
        'hide_add_to_cart' => true,
        'replacement_mode' => 'quote',
        'cta_text' => __('Ask about trade terms', 'polski'),
        'login_cta_text' => __('Log in to see the price', 'polski'),
        'custom_url' => '',
        'custom_url_target' => 'same_tab',
        'hidden_price_text' => __('The price is available once you log in or contact us.', 'polski'),
        'single_notice' => __('This product is shown in catalogue mode. Contact us for trade terms or a B2B quote.', 'polski'),
        'loop_notice' => __('See trade terms', 'polski'),
        'single_both_hidden_text' => __('Prices and online purchase are hidden for this product.', 'polski'),
        'single_price_hidden_text' => __('The price is hidden for this product.', 'polski'),
        'single_cart_hidden_text' => __('Online purchase is disabled for this product.', 'polski'),
        'show_single_cta' => true,
        'show_loop_notice' => true,
        'show_single_notice' => true,
        'show_single_restriction_text' => true,
    ],

    // Ajax search.
    'polski_search' => [
        'enabled' => false,
        'min_chars' => 2,
        'limit' => 6,
        'debounce_ms' => 180,
        'show_submit_button' => true,
        'show_image' => true,
        'show_price' => true,
        'show_unit_price' => true,
        'show_omnibus' => true,
        'show_sku' => true,
        'show_view_all_link' => true,
        'search_sku' => true,
        'search_categories' => true,
        'include_out_of_stock' => false,
        'search_label' => __('Search products', 'polski'),
        'results_label' => __('Product search results', 'polski'),
        'sku_label' => __('SKU', 'polski'),
        'placeholder' => __('Search products, SKUs or categories', 'polski'),
        'submit_button_text' => __('Search', 'polski'),
        'no_results_text' => __('No results for that search.', 'polski'),
        'view_all_text' => __('See all results', 'polski'),
    ],

    // Brands.
    'polski_brand' => [
        'enabled' => false,
        'show_on_single' => true,
        'show_on_loop' => true,
        'label' => __('Brand', 'polski'),
        'show_label' => true,
        'separator' => ', ',
        'link_terms' => true,
    ],

    // Ajax filters.
    'polski_filters' => [
        'enabled' => false,
        'show_on_shop' => true,
        'show_title' => true,
        'show_categories' => true,
        'show_brands' => true,
        'show_price' => true,
        'show_stock' => true,
        'show_sale' => true,
        'show_attributes' => true,
        'show_active_filters' => true,
        'show_counts' => true,
        'show_hierarchical_categories' => true,
        'enable_taxonomy_multiselect' => true,
        'taxonomy_multi_select_relation' => 'or',
        'enable_mobile_panel' => true,
        'enable_instant_filtering' => true,
        'instant_filtering_debounce_ms' => 350,
        'presets_json' => '',
        'archive_presets_json' => '',
        'attribute_taxonomies' => '',
        'max_attribute_taxonomies' => 4,
        'category_label' => __('Category', 'polski'),
        'category_all_text' => __('All', 'polski'),
        'brand_label' => __('Brand', 'polski'),
        'brand_all_text' => __('All', 'polski'),
        'min_price_label' => __('Price from', 'polski'),
        'max_price_label' => __('Price to', 'polski'),
        'stock_label' => __('Availability', 'polski'),
        'stock_any_text' => __('Any', 'polski'),
        'stock_instock_text' => __('In stock', 'polski'),
        'sale_label' => __('Promotions', 'polski'),
        'sale_active_text' => __('On sale only', 'polski'),
        'attribute_any_text' => __('Any option', 'polski'),
        'show_reset_link' => true,
        'submit_text' => __('Filter', 'polski'),
        'reset_text' => __('Clear filters', 'polski'),
        'title' => __('Product filters', 'polski'),
        'active_filters_label' => __('Active filters', 'polski'),
        'mobile_toggle_text' => __('Show filters', 'polski'),
        'mobile_close_text' => __('Close', 'polski'),
        'mobile_panel_title' => __('Product filters', 'polski'),
    ],

    // Wishlist.
    'polski_wishlist' => [
        'enabled' => false,
        'allow_guests' => true,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_in_account' => true,
        'show_title' => true,
        'show_product_image' => true,
        'show_product_name' => true,
        'show_price' => true,
        'show_add_to_cart' => true,
        'show_remove_button' => true,
        'grid_columns' => 4,
        'account_label' => __('Wishlist', 'polski'),
        'button_add_text' => __('Add to wishlist', 'polski'),
        'button_remove_text' => __('Remove from wishlist', 'polski'),
        'account_intro_text' => '',
        'login_required_text' => __('Log in to use the wishlist.', 'polski'),
        'product_not_found_text' => __('Product not found.', 'polski'),
        'empty_text' => __('The wishlist is empty.', 'polski'),
        'title' => __('Your wishlist', 'polski'),
    ],

    // Compare.
    'polski_compare' => [
        'enabled' => false,
        'allow_guests' => true,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_sticky_bar' => false,
        'show_in_account' => true,
        'show_product_image' => true,
        'show_add_to_cart' => true,
        'show_remove_button' => true,
        'account_label' => __('Comparison', 'polski'),
        'button_add_text' => __('Add to comparison', 'polski'),
        'button_remove_text' => __('Remove from comparison', 'polski'),
        'login_required_text' => __('Log in to use product comparison.', 'polski'),
        'product_not_found_text' => __('Product not found.', 'polski'),
        'limit_notice_text' => __('You can compare up to {limit} products at a time. The oldest one was replaced automatically.', 'polski'),
        'clear_error_text' => __('You cannot clear the comparison.', 'polski'),
        'intro_text' => '',
        'empty_text' => __('The comparison list is empty.', 'polski'),
        'title' => __('Product comparison', 'polski'),
        'compare_link_text' => __('Compare products', 'polski'),
        'clear_text' => __('Clear the comparison', 'polski'),
        'feature_label' => __('Attribute', 'polski'),
        'differences_toggle_text' => __('Show differences only', 'polski'),
        'price_label' => __('Price', 'polski'),
        'unit_price_label' => __('Unit price', 'polski'),
        'sku_label' => __('SKU', 'polski'),
        'availability_label' => __('Availability', 'polski'),
        'delivery_time_label' => __('Delivery time', 'polski'),
        'brand_label' => __('Brand', 'polski'),
        'manufacturer_label' => __('Manufacturer', 'polski'),
        'gtin_label' => __('GTIN / EAN', 'polski'),
        'description_label' => __('Short description', 'polski'),
        'max_items' => 4,
        'highlight_differences' => true,
        'show_only_differences' => false,
        'show_description' => true,
        'show_attributes' => true,
    ],

    // Quick view.
    'polski_quick_view' => [
        'enabled' => false,
        'show_on_loop' => true,
        'button_text' => __('Quick view', 'polski'),
        'modal_title' => __('Product quick view', 'polski'),
        'close_label' => __('Close', 'polski'),
        'loading_text' => __('Loading the product...', 'polski'),
        'error_text' => __('The product preview could not be loaded.', 'polski'),
        'product_not_found_text' => __('Product not found.', 'polski'),
        'sku_label' => __('SKU', 'polski'),
        'show_close_button' => true,
        'show_modal_label' => true,
        'show_title' => true,
        'show_image' => true,
        'show_gallery' => true,
        'show_price' => true,
        'show_unit_price' => true,
        'show_omnibus' => true,
        'show_sku' => true,
        'show_delivery_time' => true,
        'show_gpsr' => true,
        'show_brand' => true,
        'show_manufacturer' => true,
        'show_short_description' => true,
        'show_add_to_cart' => true,
        'show_view_product_link' => true,
        'view_product_text' => __('See the full product page', 'polski'),
        'view_product_target' => 'same_tab',
        'show_backdrop_close' => true,
    ],

    // Frequently bought together.
    'polski_fbt' => [
        'enabled' => false,
        'show_on_single' => true,
        'title' => __('Frequently bought together', 'polski'),
        'intro_text' => __('Offer a ready made bundle of complementary products and add the whole set to the cart in one click.', 'polski'),
        'button_text' => __('Add the bundle to the cart', 'polski'),
        'empty_text' => __('No products have been set up for the bundle.', 'polski'),
        'show_title' => true,
        'show_price' => true,
        'show_empty_state' => false,
        'total_label' => __('Total:', 'polski'),
        'success_text' => __('{count} products from the bundle were added to the cart.', 'polski'),
        'show_total' => true,
        'show_images' => true,
        'show_checkboxes' => true,
        'preselect_products' => true,
        'show_short_description' => false,
        'max_related_products' => 4,
    ],

    // Badges.
    'polski_badges' => [
        'enabled' => false,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_manual_badge' => true,
        'manual_badge_style' => 'accent',
        'show_secondary_badge' => true,
        'secondary_badge_style' => 'neutral',
        'show_sale_badge' => true,
        'show_new_badge' => true,
        'newness_days' => 30,
        'show_low_stock_badge' => true,
        'low_stock_threshold' => 3,
        'show_bestseller_badge' => true,
        'bestseller_threshold' => 25,
        'shape' => 'pill',
        'uppercase' => false,
        'max_badges_single' => 4,
        'max_badges_loop' => 3,
        'sale_badge_text' => __('Sale', 'polski'),
        'new_badge_text' => __('New arrival', 'polski'),
        'low_stock_badge_text' => __('Low stock', 'polski'),
        'bestseller_badge_text' => __('Bestseller', 'polski'),
    ],

    // Tab manager.
    'polski_tabs' => [
        'enabled' => false,
        'enable_global_shipping_tab' => false,
        'shipping_tab_title' => __('Delivery and payment', 'polski'),
        'shipping_tab_content' => '',
        'shipping_tab_priority' => 47,
        'enable_global_returns_tab' => false,
        'returns_tab_title' => __('Returns and complaints', 'polski'),
        'returns_tab_content' => '',
        'returns_tab_priority' => 48,
        'enable_product_tab_1' => true,
        'product_tab_1_priority' => 45,
        'enable_product_tab_2' => true,
        'product_tab_2_priority' => 46,
    ],

    // Featured video.
    'polski_featured_video' => [
        'enabled' => false,
        'show_on_single' => true,
        'position' => 'after_gallery',
        'title' => __('See the product in use', 'polski'),
        'intro_text' => '',
        'autoplay' => false,
        'show_title' => true,
        'show_intro' => false,
    ],

    // Gallery and zoom.
    'polski_gallery_zoom' => [
        'enabled' => false,
        'enable_zoom' => true,
        'zoom_scale' => 1.45,
        'enable_lightbox' => true,
        'dialog_label' => __('Product gallery preview', 'polski'),
        'close_label' => __('Close the gallery preview', 'polski'),
        'trigger_label' => __('Zoom in on the product photo', 'polski'),
        'show_backdrop_close' => true,
    ],

    // Product slider.
    'polski_slider' => [
        'enabled' => false,
        'show_on_single' => true,
        'source' => 'related',
        'title' => __('Recommended products', 'polski'),
        'limit' => 8,
        'show_title' => true,
        'show_intro_text' => false,
        'intro_text' => '',
        'show_image' => true,
        'show_price' => true,
        'show_name' => true,
        'show_add_to_cart' => true,
        'show_view_all_link' => false,
        'show_empty_state' => false,
        'empty_text' => __('There are no products to show in this section.', 'polski'),
        'view_all_text' => __('See all products', 'polski'),
        'view_all_target' => 'same_tab',
    ],

    // Pre-order.
    'polski_preorder' => [
        'enabled' => false,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_notice' => true,
        'button_text' => __('Pre-order now', 'polski'),
        'availability_text' => __('Pre-order, shipping from {date}', 'polski'),
        'notice_text' => __('This product is available for pre-order. Order now and we will ship from {date}.', 'polski'),
        'notice_title' => __('Pre-order', 'polski'),
        'show_notice_title' => false,
        'date_format' => 'd.m.Y',
        'allow_mixed_cart' => true,
        'mixed_cart_error_text' => __('Pre-order products cannot be combined with other products in the same cart.', 'polski'),
    ],

    // Waitlist.
    'polski_waitlist' => [
        'enabled' => false,
        'show_on_single' => true,
        'allow_guests' => true,
        'title' => __('Notify me when it is back', 'polski'),
        'show_title' => true,
        'intro_text' => __('Leave your email address and we will let you know when the product is back in stock.', 'polski'),
        'show_intro' => true,
        'email_label' => __('Email address', 'polski'),
        'email_placeholder' => __('Your email address', 'polski'),
        'button_text' => __('Notify me', 'polski'),
        'success_text' => __('Thank you. You are on the waitlist.', 'polski'),
        'privacy_label' => __('I agree to be contacted by email about the availability of this product.', 'polski'),
        'product_not_found_text' => __('Product not found.', 'polski'),
        'disabled_text' => __('The waitlist is not available for this product.', 'polski'),
        'invalid_email_text' => __('Enter a valid email address.', 'polski'),
        'privacy_error_text' => __('You have to accept the email contact consent.', 'polski'),
        'login_required_text' => __('Log in to join the waitlist.', 'polski'),
        'notify_subject' => __('Back in stock: {product_name}', 'polski'),
        'notify_intro_text' => __('{product_name} is back in stock.', 'polski'),
        'notify_outro_text' => __('If you no longer want messages like this, simply ignore this email.', 'polski'),
    ],

    // Product add-ons.
    'polski_addons' => [
        'enabled' => false,
        'show_on_single' => true,
        'section_title' => __('Product add-ons', 'polski'),
        'section_intro' => __('Set up the add-ons and services that go with this product.', 'polski'),
        'show_price_inline' => true,
        'show_descriptions' => true,
        'field_style' => 'boxed',
        'required_badge_text' => __('Required', 'polski'),
        'optional_badge_text' => __('Optional', 'polski'),
        'select_placeholder' => __('Choose an option', 'polski'),
        'text_placeholder' => __('Enter a value', 'polski'),
        'textarea_placeholder' => __('Enter the details', 'polski'),
        'textarea_rows' => 3,
        'price_prefix' => '+',
    ],

    // Product bundles.
    'polski_bundles' => [
        'enabled' => false,
        'show_on_single' => true,
        'title' => __('Buy as a bundle', 'polski'),
        'intro_text' => __('Combine the main product with accessories and buy the whole set as one package.', 'polski'),
        'button_text' => __('Add the bundle to the cart', 'polski'),
        'selection_required_text' => __('Choose at least one add-on product for the bundle.', 'polski'),
        'success_text' => __('The bundle was added to the cart.', 'polski'),
        'show_total' => true,
        'show_quantities' => true,
        'bundle_total_label' => __('Bundle price', 'polski'),
        'included_label' => __('in the bundle', 'polski'),
        'quantity_format' => __('x {quantity}', 'polski'),
        'discount_label' => __('You save', 'polski'),
    ],

    // Infinite scrolling.
    'polski_infinite_scroll' => [
        'enabled' => false,
        'mode' => 'button',
        'button_text' => __('Load more products', 'polski'),
        'loading_text' => __('Loading products...', 'polski'),
        'error_text' => __('More products could not be loaded.', 'polski'),
        'end_text' => __('That is all the products.', 'polski'),
        'loaded_text' => __('More products have been loaded.', 'polski'),
        'show_on_shop' => true,
        'show_on_taxonomies' => true,
        'auto_after_pages' => 0,
        'show_status' => true,
        'show_button_in_auto_mode' => false,
    ],

    // Popup.
    'polski_popup' => [
        'enabled' => false,
        'title' => __('A question about the product or about trade terms?', 'polski'),
        'content' => __('Contact us for a B2B quote, a wholesale discount or help choosing a product.', 'polski'),
        'cta_text' => __('Go to contact', 'polski'),
        'show_title' => true,
        'show_close_button' => true,
        'close_label' => __('Close the popup', 'polski'),
        'dialog_label' => __('Promotional popup', 'polski'),
        'cta_url' => '',
        'fallback_cta_url' => 'account',
        'show_cta' => true,
        'cta_target' => 'same_tab',
        'show_backdrop_close' => true,
        'show_on_home' => true,
        'show_on_shop' => true,
        'show_on_product' => false,
        'show_on_cart' => false,
        'show_on_checkout' => false,
        'delay_seconds' => 4,
        'frequency_days' => 7,
    ],

    // Food module.
    'polski_food' => [
        'enabled' => false,
        'show_ingredients' => true,
        'show_allergens' => true,
        'show_nutrients' => true,
        'show_nutri_score' => true,
        'show_alcohol' => true,
        'show_origin' => true,
        'show_distributor' => true,
        'show_net_filling' => true,
        'ingredients_label' => __('Ingredients', 'polski'),
        'allergens_label' => __('Allergens', 'polski'),
        'nutrients_caption_prefix' => __('Nutrition per', 'polski'),
        'nutrients_column_name' => __('Nutrient', 'polski'),
        'nutrients_column_value' => __('Value', 'polski'),
        'nutrients_reference_unit' => __('100 g', 'polski'),
        'nutri_score_label' => __('Nutri-Score', 'polski'),
        'alcohol_label' => __('Alcoholic strength', 'polski'),
        'alcohol_suffix' => __('% vol.', 'polski'),
        'origin_label' => __('Country of origin', 'polski'),
        'distributor_label' => __('Distributor', 'polski'),
        'net_filling_label' => __('Net quantity', 'polski'),
    ],

    // Trust Badges.
    'polski_trust_badges' => [
        'show_on_product' => true,
        'show_on_cart' => true,
        'show_on_checkout' => true,
    ],

    // Live Cart Sidebar.
    'polski_live_cart' => [
        'auto_open' => true,
        'show_subtotal' => true,
        'show_shipping_notice' => true,
        'free_shipping_threshold' => 0,
        'position' => 'right',
        'overlay' => true,
    ],

    // Social Proof.
    'polski_social_proof' => [
        'display_interval' => 8,
        'display_duration' => 5,
        'position' => 'bottom-left',
        'anonymize_name' => false,
        'hide_on_mobile' => false,
        /* translators: 1: customer first name (possibly anonymized), 2: product name */
        'message_template' => __('%1$s bought %2$s', 'polski'),
        /* translators: %d: number of minutes since the order */
        'time_ago_minutes' => __('%d min ago', 'polski'),
        /* translators: %d: number of hours since the order */
        'time_ago_hours' => __('%d h ago', 'polski'),
    ],

    // Product Q&A.
    'polski_product_qa' => [
        'tab_title' => __('Questions and answers', 'polski'),
        'ask_placeholder' => __('Ask a question about this product...', 'polski'),
        'ask_button' => __('Ask a question', 'polski'),
        'answer_button' => __('Reply', 'polski'),
        'no_questions' => __('No questions yet. Ask the first one.', 'polski'),
    ],

    // Price History Chart.
    'polski_price_history' => [
        'days' => 30,
        'show_min_max' => true,
        'color' => '#0369a1',
        'title' => __('Price history', 'polski'),
        'lowest_label' => __('Lowest', 'polski'),
        'highest_label' => __('Highest', 'polski'),
    ],

    // FAQ.
    'polski_faq' => [
        'section_title' => __('Frequently asked questions', 'polski'),
    ],

    // AI Feed: Markdown content negotiation for AI agents.
    'polski_ai_feed' => [
        'enabled' => true,
        'post_types' => ['post', 'page', 'product'],
        'llms_txt_enabled' => true,
    ],

    // B2B checkout: company toggle, NIP / REGON / IBAN.
    'polski_b2b' => [
        'enabled' => true,
        'show_company_toggle' => true,
        'show_needs_invoice_toggle' => false,
        'nip' => true,
        'regon' => false,
        'iban' => false,
    ],

    // Consent Manager: cookie banner, categories, Google Consent Mode v2.
    'polski_consent_manager' => [
        'category_analytics' => true,
        'category_marketing' => true,
        'category_preferences' => true,
        'heading' => '',
        'banner_text' => __('We use cookies and similar technologies to run the site, measure traffic and personalise content. You can accept all of them, reject the optional ones, or manage your choices yourself.', 'polski'),
        'accept_label' => __('Accept all', 'polski'),
        'reject_label' => __('Reject optional', 'polski'),
        'manage_label' => __('Manage', 'polski'),
        'save_label' => __('Save choices', 'polski'),
        'position' => 'bottom',
        'google_consent_mode' => true,
    ],

    // Tracking Tags: consent-gated client-side tags for marketing and analytics
    // providers. The merchant enters their own ID/domain per provider. Ad pixels
    // gate under the `marketing` consent category, analytics tools under
    // `analytics`. GA4 / GTM are handled separately by the DataLayer module.
    'polski_tracking_tags' => [
        'meta_pixel_enabled' => false,
        'meta_pixel_id' => '',
        'tiktok_enabled' => false,
        'tiktok_id' => '',
        'microsoft_ads_enabled' => false,
        'microsoft_ads_id' => '',
        'clarity_enabled' => false,
        'clarity_id' => '',
        'linkedin_enabled' => false,
        'linkedin_id' => '',
        'pinterest_enabled' => false,
        'pinterest_id' => '',
        'matomo_enabled' => false,
        'matomo_site_id' => '',
        'matomo_url' => '',
        'plausible_enabled' => false,
        'plausible_domain' => '',
        'posthog_enabled' => false,
        'posthog_key' => '',
        'twitter_enabled' => false,
        'twitter_id' => '',
        'google_ads_enabled' => false,
        'google_ads_id' => '',
        'hotjar_enabled' => false,
        'hotjar_id' => '',
        'inspectlet_enabled' => false,
        'inspectlet_id' => '',
        'crazy_egg_enabled' => false,
        'crazy_egg_id' => '',
        'simple_analytics_enabled' => false,
    ],

    // Custom Integrations: merchant-supplied snippets emitted to head or footer,
    // each assigned a consent category and gated through the Consent Manager so
    // it only runs after the matching category is granted. The repeatable list is
    // stored as a JSON-encoded string under `snippets`.
    'polski_custom_integrations' => [
        'snippets' => '',
    ],

    // Safe Fonts: reduce and gate external Google Fonts requests. `optimize`
    // appends display=swap and emits preconnect hints; `gate_until_consent`
    // defers the Google Fonts stylesheet until the chosen consent category is
    // granted. Self-hosting font files is out of scope for v1.
    'polski_safe_fonts' => [
        'optimize' => true,
        'gate_until_consent' => false,
        'consent_category' => 'preferences',
    ],

    // Custom Triggers: merchant-defined dataLayer events fired on simple page
    // conditions (URL contains, or click on a CSS selector). The repeatable list
    // is stored as a JSON-encoded string under `triggers`. A trigger may be
    // gated behind a consent category.
    'polski_custom_triggers' => [
        'triggers' => '',
    ],

    // DSA module: report form, contact email, per-product widget.
    'polski_dsa' => [
        'contact_email' => '',
        'form_title' => __('Report illegal content (DSA)', 'polski'),
        'form_intro' => __('Use the form below to report content you consider illegal under the Digital Services Act.', 'polski'),
        'product_widget_enabled' => false,
        'product_widget_position' => 'after_summary',
    ],
];
