<?php

declare(strict_types=1);

defined('ABSPATH') || exit;
/**
 * Default settings for the Polish market.
 *
 * These are applied on first activation. Each key maps to a WordPress option.
 * Values are only set if the option does not already exist.
 */
return [
    // General.
    'polski_general' => [
        'small_business' => false,
        'remove_data_on_uninstall' => false,
        'bdo_number' => '',
        'dispute_resolution_enabled' => true,
        'dispute_resolution_text' => __('Platforma ODR: https://ec.europa.eu/consumers/odr', 'polski'),
        'admin_pages_generated_notice' => __('Gotowe! Wygenerowaliśmy dla Ciebie wstępne szkice stron prawnych. Przejrzyj je, dostosuj do swoich potrzeb i śmiało opublikuj.', 'polski'),
        'admin_modules_saved_notice' => __('Moduły zapisane.', 'polski'),
        'admin_setup_note_title' => __('Skonfiguruj Polski dla Twojego sklepu', 'polski'),
        'admin_setup_note_content' => __('Jeszcze chwila i sklep będzie gotowy. Przejrzyj moduły, ustaw strony prawne i domknij konfigurację w panelu Polski.', 'polski'),
        'admin_setup_note_button' => __('Otwórz konfigurację Polski', 'polski'),
        'admin_status_active' => __('Aktywna', 'polski'),
        'admin_status_inactive' => __('Wyłączona', 'polski'),
        'admin_status_unconfigured' => __('Nieskonfigurowany', 'polski'),
        'admin_legal_pages_card_title' => __('Strony prawne', 'polski'),
        'admin_legal_pages_card_progress' => __('Masz już za sobą {done} z {total} kroków. Znakomicie!', 'polski'),
        'admin_vat_card_title' => __('Wyświetlanie podatku', 'polski'),
        'admin_vat_small_business_text' => __('Zwolnienie podmiotowe (art. 113)', 'polski'),
        'admin_vat_standard_text' => __('Standardowy VAT', 'polski'),
        'admin_doi_card_title' => __('Podwójna weryfikacja (DOI)', 'polski'),
        'admin_legal_pages_section_title' => __('Strony prawne', 'polski'),
        'admin_legal_pages_table_page' => __('Strona', 'polski'),
        'admin_legal_pages_table_status' => __('Status', 'polski'),
        'admin_legal_pages_published' => __('Opublikowana', 'polski'),
        'admin_legal_pages_draft' => __('Szkic', 'polski'),
        'admin_legal_pages_missing' => __('Nieutworzona', 'polski'),
        'admin_edit_button_text' => __('Edytuj', 'polski'),
        'admin_generate_pages_empty_text' => __('Nie utworzono jeszcze stron prawnych. Wygeneruj je, aby rozpocząć.', 'polski'),
        'admin_generate_pages_button_text' => __('Wygeneruj strony prawne', 'polski'),
        'admin_next_steps_title' => __('Kolejne kroki', 'polski'),
        'admin_next_steps_publish_pages' => __('Opublikuj swoje strony prawne, Regulamin, Politykę prywatności, Prawo odstąpienia i Reklamacje.', 'polski'),
        /* translators: %s is the WooCommerce tax settings URL. */
        'admin_next_steps_tax' => __('Skonfiguruj <a href="%s">stawki VAT</a> w WooCommerce dla polskiego rynku, 23%%, 8%%, 5%% i 0%%.', 'polski'),
        /* translators: %s is the WooCommerce shipping zones URL. */
        'admin_next_steps_shipping' => __('Skonfiguruj <a href="%s">strefy wysyłki</a> dla dostaw w Polsce.', 'polski'),
        /* translators: %s is the WooCommerce product edit URL for Polski product data. */
        'admin_next_steps_products' => __('Uzupełnij dane produktów, dodaj ceny jednostkowe i czasy dostawy w <a href="%s">zakładce Polski</a> dla każdego produktu.', 'polski'),
        /* translators: %s is the WooCommerce checkout page URL. */
        'admin_next_steps_checkout' => __('Przetestuj checkout, dodaj produkt do koszyka i sprawdź checkboxy prawne oraz tekst przycisku na <a href="%s">stronie zamówienia</a>.', 'polski'),
        'admin_omnibus_plugin_detected_text' => __('wykryta, dane synchronizowane', 'polski'),
        'admin_omnibus_plugin_missing_text' => __('niezainstalowana', 'polski'),
        'admin_omnibus_no_external_text' => __('Żadna zewnętrzna wtyczka Omnibus nie jest zainstalowana. Polski używa wbudowanego systemu śledzenia cen.', 'polski'),
        'admin_omnibus_external_active_text' => __('Zewnętrzna wtyczka wykryta. Polski korzysta z jej danych zamiast wbudowanego systemu.', 'polski'),
        'admin_integration_detected_text' => __('wykryta, integracja aktywna', 'polski'),
        'admin_integration_missing_text' => __('niewykryta', 'polski'),
        'admin_checkout_toolkit_no_external_text' => __('Nie wykryto wspieranych rozszerzeń checkoutu i cookies. Polski działa nadal samodzielnie.', 'polski'),
        'admin_checkout_toolkit_external_active_text' => __('Wykryto wspierane rozszerzenia checkoutu, cookies lub danych produktowych. Polski może dopasować integrację do aktywnego zestawu.', 'polski'),
        'admin_payment_no_external_text' => __('Nie wykryto wspieranych polskich bramek płatności. Polski używa własnych ustawień checkoutu bez dodatkowych integracji.', 'polski'),
        'admin_payment_external_active_text' => __('Wykryto polskie bramki płatności. Polski może dopasować checkout i komunikaty prawne do aktywnych metod.', 'polski'),
    ],

    // Price display.
    'polski_prices' => [
        'tax_display_mode' => 'brutto',
        'unit_price_enabled' => true,
        'unit_price_text' => __('{price} / {unit}', 'polski'),
        'shipping_costs_notice_enabled' => true,
        'shipping_costs_text' => __('plus koszty wysyłki', 'polski'),
        'from_price_enabled' => true,
        'from_price_text' => __('od {price}', 'polski'),
    ],

    // Omnibus directive.
    'polski_omnibus' => [
        'enabled' => true,
        'days' => 30,
        'display_text' => __('Najniższa cena z ostatnich {days} dni: {price}', 'polski'),
        'display_on_sale_only' => true,
        'prune_after_days' => 90,
    ],

    // Review request emails.
    'polski_review_requests' => [
        'delay_days' => 7,
        'email_subject' => __('Jak oceniasz swoje zakupy? Zostaw opinię', 'polski'),
        'email_intro' => __('Cześć {first_name}, dziękujemy za ostatnie zakupy. Będziemy wdzięczni za Twoją opinię.', 'polski'),
        'review_cta_text' => __('Zostaw opinię', 'polski'),
        'optout_link_text' => __('Zrezygnuj z próśb o opinię', 'polski'),
        'optout_success_text' => __('Nie będziemy już wysyłać próśb o opinię.', 'polski'),
    ],

    // Minimum order rules.
    'polski_minimum_order' => [
        'min_value' => 0,
        'min_quantity' => 0,
        'exclude_sale_items' => false,
        'min_value_message' => __('Minimalna wartość zamówienia to {min_value}. Aktualna wartość koszyka: {current_value}.', 'polski'),
        'min_quantity_message' => __('Minimalna liczba produktów w zamówieniu to {min_quantity}. Aktualna liczba: {current_quantity}.', 'polski'),
    ],

    // Checkout.
    'polski_checkout' => [
        'order_button_text' => __('Zamawiam z obowiązkiem zapłaty', 'polski'),
        'terms_checkbox_enabled' => true,
        /* translators: %s is the terms and conditions page URL. */
        'terms_checkbox_label' => __('Zapoznałem się i akceptuję <a href="%s" target="_blank">Regulamin sklepu</a>.', 'polski'),
        'terms_checkbox_error' => __('Musisz zaakceptować Regulamin, aby złożyć zamówienie.', 'polski'),
        'terms_checkbox_description' => __('Akceptacja Regulaminu sklepu.', 'polski'),
        'privacy_checkbox_enabled' => true,
        /* translators: %s is the privacy policy page URL. */
        'privacy_checkbox_label' => __('Zapoznałem się i akceptuję <a href="%s" target="_blank">Politykę prywatności</a>.', 'polski'),
        'privacy_checkbox_error' => __('Musisz zaakceptować Politykę prywatności.', 'polski'),
        'privacy_checkbox_description' => __('Akceptacja Polityki prywatności.', 'polski'),
        'withdrawal_checkbox_enabled' => true,
        /* translators: %s is the withdrawal information page URL. */
        'withdrawal_checkbox_label' => __('Potwierdzam, że zostałem poinformowany o <a href="%s" target="_blank">prawie odstąpienia od umowy</a> w ciągu 14 dni.', 'polski'),
        'withdrawal_checkbox_error' => __('Musisz potwierdzić zapoznanie się z informacją o prawie odstąpienia.', 'polski'),
        'withdrawal_checkbox_description' => __('Potwierdzenie informacji o 14-dniowym prawie odstąpienia.', 'polski'),
        'digital_waiver_checkbox_enabled' => false,
        'digital_waiver_checkbox_label' => __('Wyrażam zgodę na rozpoczęcie dostarczania treści cyfrowych przed upływem terminu do odstąpienia od umowy i przyjmuję do wiadomości utratę prawa odstąpienia.', 'polski'),
        'digital_waiver_checkbox_error' => __('Musisz wyrazić zgodę na natychmiastowe dostarczenie treści cyfrowych.', 'polski'),
        'digital_waiver_checkbox_description' => __('Zrzeczenie się prawa odstąpienia dla treści cyfrowych.', 'polski'),
        'parcel_delivery_checkbox_enabled' => false,
        'parcel_delivery_checkbox_label' => __('Wyrażam zgodę na otrzymywanie powiadomień SMS/email o statusie dostawy przesyłki.', 'polski'),
        'parcel_delivery_checkbox_description' => __('Opcjonalna zgoda na powiadomienia o dostawie.', 'polski'),
        'review_reminder_checkbox_enabled' => false,
        'review_reminder_checkbox_label' => __('Wyrażam zgodę na otrzymanie przypomnienia o wystawieniu opinii drogą mailową po zakupie.', 'polski'),
        'review_reminder_checkbox_description' => __('Opcjonalna zgoda na przypomnienia o opinii.', 'polski'),
        'marketing_checkbox_enabled' => false,
        'marketing_checkbox_label' => __('Wyrażam zgodę na otrzymywanie komunikacji marketingowej i newslettera.', 'polski'),
        'marketing_checkbox_description' => __('Opcjonalna zgoda marketingowa.', 'polski'),
    ],

    // Emails.
    'polski_emails' => [
        'attach_terms' => true,
        'attach_privacy' => false,
        'attach_withdrawal' => true,
    ],

    // Withdrawal.
    'polski_withdrawal' => [
        'button_text' => __('Odstąp od umowy', 'polski'),
        'form_title' => __('Wniosek o odstąpienie od umowy', 'polski'),
        'form_intro_text' => __('Nawiążesz do zamówienia nr #{order_number} z dnia {order_date}.', 'polski'),
        'legal_notice_text' => __('Zgodnie z polskim prawem konsumenckim masz prawo odstąpić od umowy w ciągu 14 dni bez podania przyczyny.', 'polski'),
        'items_heading' => __('Produkty w zamówieniu', 'polski'),
        'column_product' => __('Produkt', 'polski'),
        'column_quantity' => __('Ilość', 'polski'),
        'column_price' => __('Cena', 'polski'),
        'exempt_notice_text' => __('(Ten produkt jest wyłączony z prawa odstąpienia)', 'polski'),
        'reason_label' => __('Powód odstąpienia (opcjonalnie)', 'polski'),
        'submit_button_text' => __('Wyślij wniosek o odstąpienie', 'polski'),
        'invalid_nonce_text' => __('Coś poszło nie tak po naszej stronie. Spróbuj ponownie.', 'polski'),
        'order_not_found_text' => __('Nie znaleźliśmy tego zamówienia.', 'polski'),
        'permission_error_text' => __('Nie masz uprawnień, aby odstąpić od tego zamówienia.', 'polski'),
        'success_text' => __('Twój wniosek o odstąpienie został przyjęty. Wkrótce wyślemy e-mail z potwierdzeniem.', 'polski'),
        'not_eligible_text' => __('To zamówienie nie kwalifikuje się do odstąpienia.', 'polski'),
        'status_heading' => __('Wniosek o odstąpienie', 'polski'),
        'status_label' => __('Status', 'polski'),
        'submitted_label' => __('Złożony', 'polski'),
        'requested_order_note' => __('Klient złożył wniosek o odstąpienie od umowy.', 'polski'),
        'confirmed_order_note' => __('Wniosek o odstąpienie został potwierdzony.', 'polski'),
        'status_date_format' => 'Y-m-d H:i',
        'email_subject' => __('Potwierdzenie wniosku o odstąpienie od zamówienia nr #{order_number}', 'polski'),
        'email_heading' => __('Odstąpienie potwierdzone', 'polski'),
        'email_greeting' => __('Cześć {name},', 'polski'),
        'email_intro_text' => __('Twoje odstąpienie od umowy dla zamówienia nr #{order_number} zostało potwierdzone.', 'polski'),
        'email_reason_label' => __('Twój powód', 'polski'),
        'email_return_instruction' => __('Prosimy o zwrot produktów na powyższy adres w ciągu 14 dni:', 'polski'),
        'email_additional_content' => __('Zwrot środków nastąpi w ciągu 14 dni od momentu otrzymania przez nas wracanych produktów.', 'polski'),
    ],

    // Tax.
    'polski_taxes' => [
        'vat_notice_text' => __('w tym {rate}% VAT', 'polski'),
        'vat_exempt_notice' => __('Zwolniony z VAT na podstawie art. 113 ust. 1 ustawy o VAT', 'polski'),
    ],

    // Delivery times.
    'polski_delivery' => [
        'default_delivery_time' => '',
        'display_format' => __('Czas dostawy: {time}', 'polski'),
        'show_in_loop' => false,
    ],

    // Double opt-in.
    'polski_doi' => [
        'enabled' => false,
        'cleanup_days' => 7,
        'login_blocked_text' => __('Twoje konto czeka na aktywację! Zerknij do swojej skrzynki e-mail i kliknij w przesłany przez nas link.', 'polski'),
        'invalid_link_text' => __('Nieprawidłowy link aktywacyjny.', 'polski'),
        'activation_success_text' => __('Wspaniale! Twoje konto jest już aktywowane. Możesz się teraz śmiało zalogować.', 'polski'),
        'email_subject' => __('Aktywuj swoje konto w {site_title}', 'polski'),
        'email_heading' => __('Potwierdź swój adres email', 'polski'),
        'email_greeting' => __('Cześć {name},', 'polski'),
        'email_intro_html' => __('Dziękujemy za założenie konta. Kliknij przycisk poniżej, aby aktywować konto:', 'polski'),
        'email_button_text' => __('Aktywuj konto', 'polski'),
        'email_link_intro' => __('Jeśli wolisz, skopiuj i wklej ten link do przeglądarki:', 'polski'),
        'email_intro_plain' => __('Dziękujemy za założenie konta. Odwiedź poniższy link, aby aktywować konto:', 'polski'),
        'additional_content' => __('Jeśli to nie Ty zakładałeś/-aś u nas konto, nie przejmuj się i po prostu wykasuj tę wiadomość.', 'polski'),
    ],

    // Request a quote.
    'polski_quote' => [
        'enabled' => false,
        'availability' => 'selected',
        'show_on_single' => true,
        'show_on_loop' => false,
        'allow_guest' => true,
        'replace_add_to_cart' => false,
        'hide_prices' => false,
        'button_text' => __('Zapytaj o wycenę', 'polski'),
        'modal_title' => __('Zapytaj o indywidualną wycenę', 'polski'),
        'intro_text' => __('Wypełnij krótki formularz, a wrócimy z wyceną dopasowaną do Twojego zamówienia.', 'polski'),
        'close_label' => __('Zamknij formularz wyceny', 'polski'),
        'login_required_text' => __('Zaloguj się, aby wysłać zapytanie ofertowe dla tego produktu.', 'polski'),
        'name_label' => __('Imię i nazwisko', 'polski'),
        'email_label' => __('Email', 'polski'),
        'phone_label' => __('Telefon', 'polski'),
        'company_label' => __('Firma', 'polski'),
        'nip_label' => __('NIP', 'polski'),
        'postcode_label' => __('Kod pocztowy', 'polski'),
        'quantity_label' => __('Ilość', 'polski'),
        'message_label' => __('Szczegóły zapytania', 'polski'),
        'message_placeholder' => __('Napisz czego potrzebujesz, jaki masz termin i jakie są założenia zamówienia.', 'polski'),
        'submit_text' => __('Wyślij zapytanie', 'polski'),
        'success_text' => __('Dziękujemy. Twoje zapytanie zostało wysłane, wrócimy z odpowiedzią tak szybko, jak to możliwe.', 'polski'),
        'price_placeholder_text' => __('Cena dostępna po wycenie', 'polski'),
        'invalid_contact_text' => __('Uzupełnij poprawnie imię i adres email.', 'polski'),
        'phone_required_text' => __('Podaj numer telefonu do kontaktu.', 'polski'),
        'company_required_text' => __('Podaj nazwę firmy.', 'polski'),
        'nip_required_text' => __('Podaj numer NIP.', 'polski'),
        'nip_invalid_text' => __('Podaj poprawny numer NIP.', 'polski'),
        'postcode_required_text' => __('Podaj kod pocztowy.', 'polski'),
        'privacy_required_text' => __('Musisz zaakceptować zgodę prywatności.', 'polski'),
        'minimum_quantity_text' => __('Minimalna ilość dla tego zapytania to {quantity}.', 'polski'),
        'save_error_text' => __('Nie udało się zapisać zapytania. Spróbuj ponownie.', 'polski'),
        'product_unavailable_text' => __('Nie udało się przygotować zapytania dla tego produktu.', 'polski'),
        'recipient_email' => '',
        'require_company' => true,
        'require_phone' => true,
        'require_nip' => false,
        'require_postcode' => false,
        'privacy_required' => true,
        'privacy_label' => __('Akceptuję politykę prywatności i zgadzam się na kontakt w sprawie wyceny.', 'polski'),
        'admin_email_subject' => __('Nowe zapytanie ofertowe - {product_name}', 'polski'),
        'customer_email_subject' => __('Potwierdzenie zapytania ofertowego - {product_name}', 'polski'),
        'customer_email_enabled' => true,
        'admin_page_title' => __('Zapytania ofertowe', 'polski'),
        'admin_success_notice' => __('Status zapytania został zaktualizowany.', 'polski'),
        'admin_filter_all_label' => __('Wszystkie', 'polski'),
        'admin_column_date' => __('Data', 'polski'),
        'admin_column_product' => __('Produkt', 'polski'),
        'admin_column_customer' => __('Klient', 'polski'),
        'admin_column_company' => __('Firma / NIP', 'polski'),
        'admin_column_quantity' => __('Ilość', 'polski'),
        'admin_column_status' => __('Status', 'polski'),
        'admin_column_actions' => __('Akcje', 'polski'),
        'admin_empty_text' => __('Brak zapytań ofertowych.', 'polski'),
        'admin_postcode_label' => __('Kod', 'polski'),
        'admin_date_format' => 'Y-m-d H:i',
    ],

    // Catalog mode.
    'polski_catalog' => [
        'enabled' => false,
        'availability' => 'selected',
        'audience' => 'guests_only',
        'selected_roles' => '',
        'hide_prices' => true,
        'hide_add_to_cart' => true,
        'replacement_mode' => 'quote',
        'cta_text' => __('Zapytaj o warunki handlowe', 'polski'),
        'login_cta_text' => __('Zaloguj się, aby zobaczyć ofertę', 'polski'),
        'custom_url' => '',
        'custom_url_target' => 'same_tab',
        'hidden_price_text' => __('Cena dostępna po zalogowaniu lub po kontakcie z obsługą.', 'polski'),
        'single_notice' => __('Produkt dostępny w trybie katalogowym. Skontaktuj się z nami, aby uzyskać warunki handlowe lub ofertę B2B.', 'polski'),
        'loop_notice' => __('Zobacz warunki handlowe', 'polski'),
        'single_both_hidden_text' => __('Ceny i zakup online są ukryte dla tego produktu.', 'polski'),
        'single_price_hidden_text' => __('Cena jest ukryta dla tego produktu.', 'polski'),
        'single_cart_hidden_text' => __('Zakup online jest wyłączony dla tego produktu.', 'polski'),
        'show_single_cta' => true,
        'show_loop_notice' => true,
        'show_single_notice' => true,
        'show_single_restriction_text' => true,
    ],

    // Ajax search.
    'polski_search' => [
        'enabled' => false,
        'min_chars' => 2,
        'limit' => 6,
        'debounce_ms' => 180,
        'show_submit_button' => true,
        'show_image' => true,
        'show_price' => true,
        'show_unit_price' => true,
        'show_omnibus' => true,
        'show_sku' => true,
        'show_view_all_link' => true,
        'search_sku' => true,
        'search_categories' => true,
        'include_out_of_stock' => false,
        'search_label' => __('Szukaj produktów', 'polski'),
        'results_label' => __('Wyniki wyszukiwania produktów', 'polski'),
        'sku_label' => __('SKU', 'polski'),
        'placeholder' => __('Szukaj produktów, kodów SKU lub kategorii', 'polski'),
        'submit_button_text' => __('Szukaj', 'polski'),
        'no_results_text' => __('Brak wyników dla podanego zapytania.', 'polski'),
        'view_all_text' => __('Zobacz wszystkie wyniki', 'polski'),
    ],

    // Brands.
    'polski_brand' => [
        'enabled' => false,
        'show_on_single' => true,
        'show_on_loop' => true,
        'label' => __('Marka', 'polski'),
        'show_label' => true,
        'separator' => ', ',
        'link_terms' => true,
    ],

    // Ajax filters.
    'polski_filters' => [
        'enabled' => false,
        'show_on_shop' => true,
        'show_title' => true,
        'show_categories' => true,
        'show_brands' => true,
        'show_price' => true,
        'show_stock' => true,
        'show_sale' => true,
        'show_attributes' => true,
        'show_active_filters' => true,
        'show_counts' => true,
        'show_hierarchical_categories' => true,
        'enable_taxonomy_multiselect' => true,
        'taxonomy_multi_select_relation' => 'or',
        'enable_mobile_panel' => true,
        'enable_instant_filtering' => true,
        'instant_filtering_debounce_ms' => 350,
        'presets_json' => '',
        'archive_presets_json' => '',
        'attribute_taxonomies' => '',
        'max_attribute_taxonomies' => 4,
        'category_label' => __('Kategoria', 'polski'),
        'category_all_text' => __('Wszystkie', 'polski'),
        'brand_label' => __('Marka', 'polski'),
        'brand_all_text' => __('Wszystkie', 'polski'),
        'min_price_label' => __('Cena od', 'polski'),
        'max_price_label' => __('Cena do', 'polski'),
        'stock_label' => __('Dostępność', 'polski'),
        'stock_any_text' => __('Dowolna', 'polski'),
        'stock_instock_text' => __('Dostępne od ręki', 'polski'),
        'sale_label' => __('Promocje', 'polski'),
        'sale_active_text' => __('Tylko promocje', 'polski'),
        'attribute_any_text' => __('Dowolny', 'polski'),
        'show_reset_link' => true,
        'submit_text' => __('Filtruj', 'polski'),
        'reset_text' => __('Wyczyść filtry', 'polski'),
        'title' => __('Filtry produktów', 'polski'),
        'active_filters_label' => __('Aktywne filtry', 'polski'),
        'mobile_toggle_text' => __('Pokaż filtry', 'polski'),
        'mobile_close_text' => __('Zamknij', 'polski'),
        'mobile_panel_title' => __('Filtry produktów', 'polski'),
    ],

    // Wishlist.
    'polski_wishlist' => [
        'enabled' => false,
        'allow_guests' => true,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_in_account' => true,
        'show_title' => true,
        'show_product_image' => true,
        'show_product_name' => true,
        'show_price' => true,
        'show_add_to_cart' => true,
        'show_remove_button' => true,
        'grid_columns' => 4,
        'account_label' => __('Ulubione', 'polski'),
        'button_add_text' => __('Dodaj do ulubionych', 'polski'),
        'button_remove_text' => __('Usuń z ulubionych', 'polski'),
        'account_intro_text' => '',
        'login_required_text' => __('Zaloguj się, aby korzystać z listy życzeń.', 'polski'),
        'product_not_found_text' => __('Nie znaleziono produktu.', 'polski'),
        'empty_text' => __('Lista ulubionych jest pusta.', 'polski'),
        'title' => __('Twoje ulubione produkty', 'polski'),
    ],

    // Compare.
    'polski_compare' => [
        'enabled' => false,
        'allow_guests' => true,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_sticky_bar' => false,
        'show_in_account' => true,
        'show_product_image' => true,
        'show_add_to_cart' => true,
        'show_remove_button' => true,
        'account_label' => __('Porównanie', 'polski'),
        'button_add_text' => __('Dodaj do porównania', 'polski'),
        'button_remove_text' => __('Usuń z porównania', 'polski'),
        'login_required_text' => __('Zaloguj się, aby korzystać z porównania produktów.', 'polski'),
        'product_not_found_text' => __('Nie znaleziono produktu.', 'polski'),
        'limit_notice_text' => __('Możesz porównać maksymalnie {limit} produkty jednocześnie. Najstarszy wpis został zastąpiony automatycznie.', 'polski'),
        'clear_error_text' => __('Nie możesz wyczyścić porównania.', 'polski'),
        'intro_text' => '',
        'empty_text' => __('Lista porównawcza jest pusta.', 'polski'),
        'title' => __('Porównanie produktów', 'polski'),
        'compare_link_text' => __('Porównaj produkty', 'polski'),
        'clear_text' => __('Wyczyść porównanie', 'polski'),
        'feature_label' => __('Cecha', 'polski'),
        'differences_toggle_text' => __('Pokazuj tylko różnice', 'polski'),
        'price_label' => __('Cena', 'polski'),
        'unit_price_label' => __('Cena jednostkowa', 'polski'),
        'sku_label' => __('SKU', 'polski'),
        'availability_label' => __('Dostępność', 'polski'),
        'delivery_time_label' => __('Czas dostawy', 'polski'),
        'brand_label' => __('Marka', 'polski'),
        'manufacturer_label' => __('Producent', 'polski'),
        'gtin_label' => __('GTIN / EAN', 'polski'),
        'description_label' => __('Krótki opis', 'polski'),
        'max_items' => 4,
        'highlight_differences' => true,
        'show_only_differences' => false,
        'show_description' => true,
        'show_attributes' => true,
    ],

    // Quick view.
    'polski_quick_view' => [
        'enabled' => false,
        'show_on_loop' => true,
        'button_text' => __('Szybki podgląd', 'polski'),
        'modal_title' => __('Szybki podgląd produktu', 'polski'),
        'close_label' => __('Zamknij', 'polski'),
        'loading_text' => __('Ładowanie produktu...', 'polski'),
        'error_text' => __('Nie udało się wczytać podglądu produktu.', 'polski'),
        'product_not_found_text' => __('Nie znaleziono produktu.', 'polski'),
        'sku_label' => __('SKU', 'polski'),
        'show_close_button' => true,
        'show_modal_label' => true,
        'show_title' => true,
        'show_image' => true,
        'show_gallery' => true,
        'show_price' => true,
        'show_unit_price' => true,
        'show_omnibus' => true,
        'show_sku' => true,
        'show_delivery_time' => true,
        'show_gpsr' => true,
        'show_brand' => true,
        'show_manufacturer' => true,
        'show_short_description' => true,
        'show_add_to_cart' => true,
        'show_view_product_link' => true,
        'view_product_text' => __('Zobacz pełną kartę produktu', 'polski'),
        'view_product_target' => 'same_tab',
        'show_backdrop_close' => true,
    ],

    // Frequently bought together.
    'polski_fbt' => [
        'enabled' => false,
        'show_on_single' => true,
        'title' => __('Często kupowane razem', 'polski'),
        'intro_text' => __('Zaproponuj klientowi gotowy zestaw produktów komplementarnych i dodaj całość do koszyka jednym kliknięciem.', 'polski'),
        'button_text' => __('Dodaj zestaw do koszyka', 'polski'),
        'empty_text' => __('Brak skonfigurowanych produktów do zestawu.', 'polski'),
        'show_title' => true,
        'show_price' => true,
        'show_empty_state' => false,
        'total_label' => __('Łącznie:', 'polski'),
        'success_text' => __('Dodano {count} produktów z zestawu do koszyka.', 'polski'),
        'show_total' => true,
        'show_images' => true,
        'show_checkboxes' => true,
        'preselect_products' => true,
        'show_short_description' => false,
        'max_related_products' => 4,
    ],

    // Badges.
    'polski_badges' => [
        'enabled' => false,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_manual_badge' => true,
        'manual_badge_style' => 'accent',
        'show_secondary_badge' => true,
        'secondary_badge_style' => 'neutral',
        'show_sale_badge' => true,
        'show_new_badge' => true,
        'newness_days' => 30,
        'show_low_stock_badge' => true,
        'low_stock_threshold' => 3,
        'show_bestseller_badge' => true,
        'bestseller_threshold' => 25,
        'shape' => 'pill',
        'uppercase' => false,
        'max_badges_single' => 4,
        'max_badges_loop' => 3,
        'sale_badge_text' => __('Promocja', 'polski'),
        'new_badge_text' => __('Nowość', 'polski'),
        'low_stock_badge_text' => __('Ostatnie sztuki', 'polski'),
        'bestseller_badge_text' => __('Bestseller', 'polski'),
    ],

    // Tab manager.
    'polski_tabs' => [
        'enabled' => false,
        'enable_global_shipping_tab' => false,
        'shipping_tab_title' => __('Dostawa i płatność', 'polski'),
        'shipping_tab_content' => '',
        'shipping_tab_priority' => 47,
        'enable_global_returns_tab' => false,
        'returns_tab_title' => __('Zwroty i reklamacje', 'polski'),
        'returns_tab_content' => '',
        'returns_tab_priority' => 48,
        'enable_product_tab_1' => true,
        'product_tab_1_priority' => 45,
        'enable_product_tab_2' => true,
        'product_tab_2_priority' => 46,
    ],

    // Featured video.
    'polski_featured_video' => [
        'enabled' => false,
        'show_on_single' => true,
        'position' => 'after_gallery',
        'title' => __('Zobacz produkt w użyciu', 'polski'),
        'intro_text' => '',
        'autoplay' => false,
        'show_title' => true,
        'show_intro' => false,
    ],

    // Gallery and zoom.
    'polski_gallery_zoom' => [
        'enabled' => false,
        'enable_zoom' => true,
        'zoom_scale' => 1.45,
        'enable_lightbox' => true,
        'dialog_label' => __('Podgląd galerii produktu', 'polski'),
        'close_label' => __('Zamknij podgląd galerii', 'polski'),
        'trigger_label' => __('Powiększ zdjęcie produktu', 'polski'),
        'show_backdrop_close' => true,
    ],

    // Product slider.
    'polski_slider' => [
        'enabled' => false,
        'show_on_single' => true,
        'source' => 'related',
        'title' => __('Polecane produkty', 'polski'),
        'limit' => 8,
        'show_title' => true,
        'show_intro_text' => false,
        'intro_text' => '',
        'show_image' => true,
        'show_price' => true,
        'show_name' => true,
        'show_add_to_cart' => true,
        'show_view_all_link' => false,
        'show_empty_state' => false,
        'empty_text' => __('Brak produktów do wyświetlenia w tej sekcji.', 'polski'),
        'view_all_text' => __('Zobacz wszystkie produkty', 'polski'),
        'view_all_target' => 'same_tab',
    ],

    // Pre-order.
    'polski_preorder' => [
        'enabled' => false,
        'show_on_single' => true,
        'show_on_loop' => true,
        'show_notice' => true,
        'button_text' => __('Zamów w przedsprzedaży', 'polski'),
        'availability_text' => __('Przedsprzedaż, wysyłka od {date}', 'polski'),
        'notice_text' => __('Ten produkt jest dostępny w przedsprzedaży. Zamów teraz, a wysyłkę zrealizujemy od {date}.', 'polski'),
        'notice_title' => __('Przedsprzedaż', 'polski'),
        'show_notice_title' => false,
        'date_format' => 'd.m.Y',
        'allow_mixed_cart' => true,
        'mixed_cart_error_text' => __('Produkty z przedsprzedaży nie mogą być łączone z innymi produktami w tym samym koszyku.', 'polski'),
    ],

    // Waitlist.
    'polski_waitlist' => [
        'enabled' => false,
        'show_on_single' => true,
        'allow_guests' => true,
        'title' => __('Powiadom mnie o dostępności', 'polski'),
        'show_title' => true,
        'intro_text' => __('Zostaw adres email, a damy znać, gdy produkt wróci na stan.', 'polski'),
        'show_intro' => true,
        'email_label' => __('Adres email', 'polski'),
        'email_placeholder' => __('Twój adres email', 'polski'),
        'button_text' => __('Powiadom mnie', 'polski'),
        'success_text' => __('Dziękujemy. Zapisaliśmy Cię na listę oczekujących.', 'polski'),
        'privacy_label' => __('Akceptuję kontakt email w sprawie dostępności tego produktu.', 'polski'),
        'product_not_found_text' => __('Nie znaleziono produktu.', 'polski'),
        'disabled_text' => __('Lista oczekujących jest niedostępna dla tego produktu.', 'polski'),
        'invalid_email_text' => __('Podaj poprawny adres email.', 'polski'),
        'privacy_error_text' => __('Musisz zaakceptować zgodę na kontakt email.', 'polski'),
        'login_required_text' => __('Zaloguj się, aby zapisać się na listę oczekujących.', 'polski'),
        'notify_subject' => __('Produkt ponownie dostępny - {product_name}', 'polski'),
        'notify_intro_text' => __('Produkt {product_name} jest ponownie dostępny.', 'polski'),
        'notify_outro_text' => __('Jeśli nie chcesz już otrzymywać takich wiadomości, po prostu zignoruj ten email.', 'polski'),
    ],

    // Product add-ons.
    'polski_addons' => [
        'enabled' => false,
        'show_on_single' => true,
        'section_title' => __('Dodatki do produktu', 'polski'),
        'section_intro' => __('Skonfiguruj dodatki i usługi powiązane z tym produktem.', 'polski'),
        'show_price_inline' => true,
        'show_descriptions' => true,
        'field_style' => 'boxed',
        'required_badge_text' => __('Wymagane', 'polski'),
        'optional_badge_text' => __('Opcjonalne', 'polski'),
        'select_placeholder' => __('Wybierz opcję', 'polski'),
        'text_placeholder' => __('Wpisz wartość', 'polski'),
        'textarea_placeholder' => __('Wpisz szczegóły', 'polski'),
        'textarea_rows' => 3,
        'price_prefix' => '+',
    ],

    // Product bundles.
    'polski_bundles' => [
        'enabled' => false,
        'show_on_single' => true,
        'title' => __('Kup w zestawie', 'polski'),
        'intro_text' => __('Połącz produkt główny z akcesoriami i kup całość w jednym pakiecie.', 'polski'),
        'button_text' => __('Dodaj zestaw do koszyka', 'polski'),
        'selection_required_text' => __('Wybierz przynajmniej jeden dodatkowy produkt do zestawu.', 'polski'),
        'success_text' => __('Dodano zestaw do koszyka.', 'polski'),
        'show_total' => true,
        'show_quantities' => true,
        'bundle_total_label' => __('Cena zestawu', 'polski'),
        'included_label' => __('w zestawie', 'polski'),
        'quantity_format' => __('x {quantity}', 'polski'),
        'discount_label' => __('Oszczędzasz', 'polski'),
    ],

    // Infinite scrolling.
    'polski_infinite_scroll' => [
        'enabled' => false,
        'mode' => 'button',
        'button_text' => __('Załaduj więcej produktów', 'polski'),
        'loading_text' => __('Ładowanie produktów...', 'polski'),
        'error_text' => __('Nie udało się załadować kolejnych produktów.', 'polski'),
        'end_text' => __('To już wszystkie produkty.', 'polski'),
        'loaded_text' => __('Załadowano kolejne produkty.', 'polski'),
        'show_on_shop' => true,
        'show_on_taxonomies' => true,
        'auto_after_pages' => 0,
        'show_status' => true,
        'show_button_in_auto_mode' => false,
    ],

    // Popup.
    'polski_popup' => [
        'enabled' => false,
        'title' => __('Masz pytanie o produkt lub warunki handlowe?', 'polski'),
        'content' => __('Skontaktuj się z nami, jeśli chcesz dostać ofertę B2B, rabat dla hurtu albo pomoc z doborem produktu.', 'polski'),
        'cta_text' => __('Przejdź do kontaktu', 'polski'),
        'show_title' => true,
        'show_close_button' => true,
        'close_label' => __('Zamknij popup', 'polski'),
        'dialog_label' => __('Popup promocyjny', 'polski'),
        'cta_url' => '',
        'fallback_cta_url' => 'account',
        'show_cta' => true,
        'cta_target' => 'same_tab',
        'show_backdrop_close' => true,
        'show_on_home' => true,
        'show_on_shop' => true,
        'show_on_product' => false,
        'show_on_cart' => false,
        'show_on_checkout' => false,
        'delay_seconds' => 4,
        'frequency_days' => 7,
    ],

    // Food module.
    'polski_food' => [
        'enabled' => false,
        'show_ingredients' => true,
        'show_allergens' => true,
        'show_nutrients' => true,
        'show_nutri_score' => true,
        'show_alcohol' => true,
        'show_origin' => true,
        'show_distributor' => true,
        'show_net_filling' => true,
        'ingredients_label' => __('Składniki', 'polski'),
        'allergens_label' => __('Alergeny', 'polski'),
        'nutrients_caption_prefix' => __('Wartości odżywcze na', 'polski'),
        'nutrients_column_name' => __('Składnik odżywczy', 'polski'),
        'nutrients_column_value' => __('Wartość', 'polski'),
        'nutrients_reference_unit' => __('100 g', 'polski'),
        'nutri_score_label' => __('Nutri-Score', 'polski'),
        'alcohol_label' => __('Zawartość alkoholu', 'polski'),
        'alcohol_suffix' => __('% vol.', 'polski'),
        'origin_label' => __('Kraj pochodzenia', 'polski'),
        'distributor_label' => __('Dystrybutor', 'polski'),
        'net_filling_label' => __('Zawartość netto', 'polski'),
    ],

    // Trust Badges.
    'polski_trust_badges' => [
        'show_on_product' => true,
        'show_on_cart' => true,
        'show_on_checkout' => true,
    ],

    // Live Cart Sidebar.
    'polski_live_cart' => [
        'auto_open' => true,
        'show_subtotal' => true,
        'show_shipping_notice' => true,
        'free_shipping_threshold' => 0,
        'position' => 'right',
        'overlay' => true,
    ],

    // Social Proof.
    'polski_social_proof' => [
        'display_interval' => 8,
        'display_duration' => 5,
        'position' => 'bottom-left',
        'anonymize_name' => false,
        'hide_on_mobile' => false,
        /* translators: 1: customer first name (possibly anonymized), 2: product name */
        'message_template' => __('%1$s kupił(a) %2$s', 'polski'),
        /* translators: %d: number of minutes since the order */
        'time_ago_minutes' => __('%d min temu', 'polski'),
        /* translators: %d: number of hours since the order */
        'time_ago_hours' => __('%d godz. temu', 'polski'),
    ],

    // Product Q&A.
    'polski_product_qa' => [
        'tab_title' => __('Pytania i odpowiedzi', 'polski'),
        'ask_placeholder' => __('Zadaj pytanie o ten produkt...', 'polski'),
        'ask_button' => __('Zadaj pytanie', 'polski'),
        'answer_button' => __('Odpowiedz', 'polski'),
        'no_questions' => __('Brak pytań. Zadaj pierwsze pytanie!', 'polski'),
    ],

    // Price History Chart.
    'polski_price_history' => [
        'days' => 30,
        'show_min_max' => true,
        'color' => '#0369a1',
        'title' => __('Historia cen', 'polski'),
        'lowest_label' => __('Najniższa', 'polski'),
        'highest_label' => __('Najwyższa', 'polski'),
    ],

    // FAQ.
    'polski_faq' => [
        'section_title' => __('Często zadawane pytania', 'polski'),
    ],

    // AI Feed: Markdown content negotiation for AI agents.
    'polski_ai_feed' => [
        'enabled' => true,
        'post_types' => ['post', 'page', 'product'],
        'llms_txt_enabled' => true,
    ],

    // B2B checkout: company toggle, NIP / REGON / IBAN.
    'polski_b2b' => [
        'enabled' => true,
        'show_company_toggle' => true,
        'show_needs_invoice_toggle' => false,
        'nip' => true,
        'regon' => false,
        'iban' => false,
    ],

    // Consent Manager: cookie banner, categories, Google Consent Mode v2.
    'polski_consent_manager' => [
        'category_analytics' => true,
        'category_marketing' => true,
        'category_preferences' => true,
        'heading' => '',
        'banner_text' => __('Używamy plików cookie i podobnych technologii, aby zapewnić działanie serwisu, mierzyć ruch i personalizować treści. Możesz zaakceptować wszystkie, odrzucić nieobowiązkowe lub samodzielnie zarządzać wyborami.', 'polski'),
        'accept_label' => __('Akceptuję wszystkie', 'polski'),
        'reject_label' => __('Odrzuć nieobowiązkowe', 'polski'),
        'manage_label' => __('Zarządzaj', 'polski'),
        'save_label' => __('Zapisz wybory', 'polski'),
        'position' => 'bottom',
        'google_consent_mode' => true,
    ],

    // Tracking Tags: consent-gated client-side tags for marketing and analytics
    // providers. The merchant enters their own ID/domain per provider. Ad pixels
    // gate under the `marketing` consent category, analytics tools under
    // `analytics`. GA4 / GTM are handled separately by the DataLayer module.
    'polski_tracking_tags' => [
        'meta_pixel_enabled' => false,
        'meta_pixel_id' => '',
        'tiktok_enabled' => false,
        'tiktok_id' => '',
        'microsoft_ads_enabled' => false,
        'microsoft_ads_id' => '',
        'clarity_enabled' => false,
        'clarity_id' => '',
        'linkedin_enabled' => false,
        'linkedin_id' => '',
        'pinterest_enabled' => false,
        'pinterest_id' => '',
        'matomo_enabled' => false,
        'matomo_site_id' => '',
        'matomo_url' => '',
        'plausible_enabled' => false,
        'plausible_domain' => '',
        'posthog_enabled' => false,
        'posthog_key' => '',
        'twitter_enabled' => false,
        'twitter_id' => '',
        'google_ads_enabled' => false,
        'google_ads_id' => '',
        'hotjar_enabled' => false,
        'hotjar_id' => '',
        'inspectlet_enabled' => false,
        'inspectlet_id' => '',
        'crazy_egg_enabled' => false,
        'crazy_egg_id' => '',
        'simple_analytics_enabled' => false,
    ],

    // Custom Integrations: merchant-supplied snippets emitted to head or footer,
    // each assigned a consent category and gated through the Consent Manager so
    // it only runs after the matching category is granted. The repeatable list is
    // stored as a JSON-encoded string under `snippets`.
    'polski_custom_integrations' => [
        'snippets' => '',
    ],

    // Safe Fonts: reduce and gate external Google Fonts requests. `optimize`
    // appends display=swap and emits preconnect hints; `gate_until_consent`
    // defers the Google Fonts stylesheet until the chosen consent category is
    // granted. Self-hosting font files is out of scope for v1.
    'polski_safe_fonts' => [
        'optimize' => true,
        'gate_until_consent' => false,
        'consent_category' => 'preferences',
    ],

    // Custom Triggers: merchant-defined dataLayer events fired on simple page
    // conditions (URL contains, or click on a CSS selector). The repeatable list
    // is stored as a JSON-encoded string under `triggers`. A trigger may be
    // gated behind a consent category.
    'polski_custom_triggers' => [
        'triggers' => '',
    ],

    // DSA module: report form, contact email, per-product widget.
    'polski_dsa' => [
        'contact_email' => '',
        'form_title' => __('Zgłoś nielegalne treści (DSA)', 'polski'),
        'form_intro' => __('Wypełnij poniższy formularz, aby zgłosić treści, które uważasz za nielegalne zgodnie z Aktem o usługach cyfrowych (DSA).', 'polski'),
        'product_widget_enabled' => false,
        'product_widget_position' => 'after_summary',
    ],
];
